/* Generated by Cython 0.9.6.10b on Sat Jan 26 11:05:45 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#ifndef WIN32
  #define __stdcall
  #define __cdecl
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n; int is_unicode;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from maps_fast */

/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pxd":1
 * cdef public class Map [ object MapObj, type MapType ]:             # <<<<<<<<<<<<<< 
 *     
 *     cdef int nglobal
 */

struct MapObj {
  PyObject_HEAD
  int nglobal;
  int nprocs;
  int nlocal;
};

/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pxd":7
 *     cdef int nlocal
 *     
 * cdef public class BlockMap(Map) [ object BlockMapObj, type BlockMapType ]:             # <<<<<<<<<<<<<< 
 *         
 *     cdef int c_owner(BlockMap self, int global_index)      
 */

struct BlockMapObj {
  struct MapObj __pyx_base;
  struct __pyx_vtabstruct_9maps_fast_BlockMap *__pyx_vtab;
};

__PYX_EXTERN_C DL_EXPORT(PyTypeObject) MapType;

/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":4
 * 
 * # cdef public class Map [ object MapObj, type MapType ]:
 * cdef class Map:             # <<<<<<<<<<<<<< 
 * 
 *     def __init__(self, nglobal, nprocs):
 */

__PYX_EXTERN_C DL_EXPORT(PyTypeObject) BlockMapType;

/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":15
 * 
 * 
 * cdef class BlockMap(Map):             # <<<<<<<<<<<<<< 
 *         
 *     cdef int c_owner(BlockMap self, int global_index):
 */

struct __pyx_vtabstruct_9maps_fast_BlockMap {
  int (*c_owner)(struct BlockMapObj *,int);
  int (*local_index)(struct BlockMapObj *,int);
  int (*global_index)(struct BlockMapObj *,int,int);
};
static struct __pyx_vtabstruct_9maps_fast_BlockMap *__pyx_vtabptr_9maps_fast_BlockMap;

static PyTypeObject *__pyx_ptype_9maps_fast_Map = 0;
static PyTypeObject *__pyx_ptype_9maps_fast_BlockMap = 0;
DL_EXPORT(PyObject) *foo(int); /*proto*/


/* Implementation of maps_fast */

static PyObject *__pyx_n___init__;
static PyObject *__pyx_n_owner;

/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":6
 * cdef class Map:
 * 
 *     def __init__(self, nglobal, nprocs):             # <<<<<<<<<<<<<< 
 *         self.nglobal = nglobal
 *         self.nprocs = nprocs
 */

static int __pyx_pf_9maps_fast_3Map___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_pf_9maps_fast_3Map___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_nglobal = 0;
  PyObject *__pyx_v_nprocs = 0;
  int __pyx_r;
  int __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"nglobal","nprocs",0};
  if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_nglobal, &__pyx_v_nprocs))) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_nglobal);
  Py_INCREF(__pyx_v_nprocs);

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":7
 * 
 *     def __init__(self, nglobal, nprocs):
 *         self.nglobal = nglobal             # <<<<<<<<<<<<<< 
 *         self.nprocs = nprocs
 *         self.nlocal = self.nglobal/self.nprocs
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_nglobal); if (unlikely((__pyx_1 == -1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  ((struct MapObj *)__pyx_v_self)->nglobal = __pyx_1;

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":8
 *     def __init__(self, nglobal, nprocs):
 *         self.nglobal = nglobal
 *         self.nprocs = nprocs             # <<<<<<<<<<<<<< 
 *         self.nlocal = self.nglobal/self.nprocs
 *         if self.nglobal%self.nprocs > 0:
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_nprocs); if (unlikely((__pyx_1 == -1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  ((struct MapObj *)__pyx_v_self)->nprocs = __pyx_1;

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":9
 *         self.nglobal = nglobal
 *         self.nprocs = nprocs
 *         self.nlocal = self.nglobal/self.nprocs             # <<<<<<<<<<<<<< 
 *         if self.nglobal%self.nprocs > 0:
 *             self.nlocal += 1
 */
  ((struct MapObj *)__pyx_v_self)->nlocal = (((struct MapObj *)__pyx_v_self)->nglobal / ((struct MapObj *)__pyx_v_self)->nprocs);

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":10
 *         self.nprocs = nprocs
 *         self.nlocal = self.nglobal/self.nprocs
 *         if self.nglobal%self.nprocs > 0:             # <<<<<<<<<<<<<< 
 *             self.nlocal += 1
 *         print self.nglobal
 */
  __pyx_2 = ((((struct MapObj *)__pyx_v_self)->nglobal % ((struct MapObj *)__pyx_v_self)->nprocs) > 0);
  if (__pyx_2) {

    /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":11
 *         self.nlocal = self.nglobal/self.nprocs
 *         if self.nglobal%self.nprocs > 0:
 *             self.nlocal += 1             # <<<<<<<<<<<<<< 
 *         print self.nglobal
 * 
 */
    ((struct MapObj *)__pyx_v_self)->nlocal += 1;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":12
 *         if self.nglobal%self.nprocs > 0:
 *             self.nlocal += 1
 *         print self.nglobal             # <<<<<<<<<<<<<< 
 * 
 * 
 */
  __pyx_3 = PyInt_FromLong(((struct MapObj *)__pyx_v_self)->nglobal); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  if (__Pyx_PrintItem(__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("maps_fast.Map.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_nglobal);
  Py_DECREF(__pyx_v_nprocs);
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":17
 * cdef class BlockMap(Map):
 *         
 *     cdef int c_owner(BlockMap self, int global_index):             # <<<<<<<<<<<<<< 
 *         cdef int o
 *         o = global_index/self.nlocal
 */

static  int __pyx_f_9maps_fast_8BlockMap_c_owner(struct BlockMapObj *__pyx_v_self,int __pyx_v_global_index) {
  int __pyx_v_o;
  int __pyx_r;
  Py_INCREF((PyObject *)__pyx_v_self);

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":19
 *     cdef int c_owner(BlockMap self, int global_index):
 *         cdef int o
 *         o = global_index/self.nlocal             # <<<<<<<<<<<<<< 
 *         return o
 *     
 */
  __pyx_v_o = (__pyx_v_global_index / __pyx_v_self->__pyx_base.nlocal);

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":20
 *         cdef int o
 *         o = global_index/self.nlocal
 *         return o             # <<<<<<<<<<<<<< 
 *     
 *     def owner(self, global_index):
 */
  __pyx_r = __pyx_v_o;
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF((PyObject *)__pyx_v_self);
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":22
 *         return o
 *     
 *     def owner(self, global_index):             # <<<<<<<<<<<<<< 
 *         return self.c_owner(global_index)
 *         
 */

static PyObject *__pyx_pf_9maps_fast_8BlockMap_owner(PyObject *__pyx_v_self, PyObject *__pyx_v_global_index); /*proto*/
static PyObject *__pyx_pf_9maps_fast_8BlockMap_owner(PyObject *__pyx_v_self, PyObject *__pyx_v_global_index) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  Py_INCREF((PyObject *)__pyx_v_self);
  Py_INCREF(__pyx_v_global_index);

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":23
 *     
 *     def owner(self, global_index):
 *         return self.c_owner(global_index)             # <<<<<<<<<<<<<< 
 *         
 *     cdef int local_index(BlockMap self, int global_index):
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_global_index); if (unlikely((__pyx_1 == -1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(((struct __pyx_vtabstruct_9maps_fast_BlockMap *)((struct BlockMapObj *)__pyx_v_self)->__pyx_vtab)->c_owner(((struct BlockMapObj *)__pyx_v_self),__pyx_1)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("maps_fast.BlockMap.owner");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF((PyObject *)__pyx_v_self);
  Py_DECREF(__pyx_v_global_index);
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":25
 *         return self.c_owner(global_index)
 *         
 *     cdef int local_index(BlockMap self, int global_index):             # <<<<<<<<<<<<<< 
 *         cdef int i
 *         i = global_index%self.nprocs
 */

static  int __pyx_f_9maps_fast_8BlockMap_local_index(struct BlockMapObj *__pyx_v_self,int __pyx_v_global_index) {
  int __pyx_v_i;
  int __pyx_r;
  Py_INCREF((PyObject *)__pyx_v_self);

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":27
 *     cdef int local_index(BlockMap self, int global_index):
 *         cdef int i
 *         i = global_index%self.nprocs             # <<<<<<<<<<<<<< 
 *         return i
 *         
 */
  __pyx_v_i = (__pyx_v_global_index % __pyx_v_self->__pyx_base.nprocs);

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":28
 *         cdef int i
 *         i = global_index%self.nprocs
 *         return i             # <<<<<<<<<<<<<< 
 *         
 *     cdef int global_index(BlockMap self, int owner, int local_index):
 */
  __pyx_r = __pyx_v_i;
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF((PyObject *)__pyx_v_self);
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":30
 *         return i
 *         
 *     cdef int global_index(BlockMap self, int owner, int local_index):             # <<<<<<<<<<<<<< 
 *         cdef int i
 *         i = owner*self.nlocal + local_index
 */

static  int __pyx_f_9maps_fast_8BlockMap_global_index(struct BlockMapObj *__pyx_v_self,int __pyx_v_owner,int __pyx_v_local_index) {
  int __pyx_v_i;
  int __pyx_r;
  Py_INCREF((PyObject *)__pyx_v_self);

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":32
 *     cdef int global_index(BlockMap self, int owner, int local_index):
 *         cdef int i
 *         i = owner*self.nlocal + local_index             # <<<<<<<<<<<<<< 
 *         return i
 * 
 */
  __pyx_v_i = ((__pyx_v_owner * __pyx_v_self->__pyx_base.nlocal) + __pyx_v_local_index);

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":33
 *         cdef int i
 *         i = owner*self.nlocal + local_index
 *         return i             # <<<<<<<<<<<<<< 
 * 
 * def test1():
 */
  __pyx_r = __pyx_v_i;
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF((PyObject *)__pyx_v_self);
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":35
 *         return i
 * 
 * def test1():             # <<<<<<<<<<<<<< 
 *     cdef BlockMap m
 *     m = BlockMap(16,4)
 */

static PyObject *__pyx_num_16;
static PyObject *__pyx_num_4;
static PyObject *__pyx_num_3;

static PyObject *__pyx_pf_9maps_fast_test1(PyObject *__pyx_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_9maps_fast_test1(PyObject *__pyx_self, PyObject *unused) {
  struct BlockMapObj *__pyx_v_m;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  long __pyx_3;
  PyObject *__pyx_4 = 0;
  __pyx_v_m = ((struct BlockMapObj *)Py_None); Py_INCREF(Py_None);
  __pyx_v_i = Py_None; Py_INCREF(Py_None);

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":37
 * def test1():
 *     cdef BlockMap m
 *     m = BlockMap(16,4)             # <<<<<<<<<<<<<< 
 *     for i from 0 <= i < 1000:
 *         m.owner(3)
 */
  __pyx_1 = PyTuple_New(2); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  Py_INCREF(__pyx_num_16);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_num_16);
  Py_INCREF(__pyx_num_4);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_num_4);
  __pyx_2 = PyObject_CallObject(((PyObject*)__pyx_ptype_9maps_fast_BlockMap), __pyx_1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (!__Pyx_TypeTest(__pyx_2, __pyx_ptype_9maps_fast_BlockMap)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_m));
  __pyx_v_m = ((struct BlockMapObj *)__pyx_2);
  __pyx_2 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":38
 *     cdef BlockMap m
 *     m = BlockMap(16,4)
 *     for i from 0 <= i < 1000:             # <<<<<<<<<<<<<< 
 *         m.owner(3)
 * 
 */
  for (__pyx_3 = 0; __pyx_3 < 1000; __pyx_3++) {
    __pyx_1 = PyInt_FromLong(__pyx_3); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_1;
    __pyx_1 = 0;

    /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":39
 *     m = BlockMap(16,4)
 *     for i from 0 <= i < 1000:
 *         m.owner(3)             # <<<<<<<<<<<<<< 
 * 
 * def test2():
 */
    __pyx_2 = PyObject_GetAttr(((PyObject *)__pyx_v_m), __pyx_n_owner); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
    __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
    Py_INCREF(__pyx_num_3);
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_num_3);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("maps_fast.test1");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF((PyObject *)__pyx_v_m);
  Py_DECREF(__pyx_v_i);
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":41
 *         m.owner(3)
 * 
 * def test2():             # <<<<<<<<<<<<<< 
 *     cdef BlockMap m
 *     m = BlockMap(16,4)
 */

static PyObject *__pyx_pf_9maps_fast_test2(PyObject *__pyx_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_9maps_fast_test2(PyObject *__pyx_self, PyObject *unused) {
  struct BlockMapObj *__pyx_v_m;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  long __pyx_3;
  PyObject *__pyx_4 = 0;
  __pyx_v_m = ((struct BlockMapObj *)Py_None); Py_INCREF(Py_None);
  __pyx_v_i = Py_None; Py_INCREF(Py_None);

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":43
 * def test2():
 *     cdef BlockMap m
 *     m = BlockMap(16,4)             # <<<<<<<<<<<<<< 
 *     for i from 0 <= i < 1000:
 *         m.owner(3)
 */
  __pyx_1 = PyTuple_New(2); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  Py_INCREF(__pyx_num_16);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_num_16);
  Py_INCREF(__pyx_num_4);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_num_4);
  __pyx_2 = PyObject_CallObject(((PyObject*)__pyx_ptype_9maps_fast_BlockMap), __pyx_1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (!__Pyx_TypeTest(__pyx_2, __pyx_ptype_9maps_fast_BlockMap)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_m));
  __pyx_v_m = ((struct BlockMapObj *)__pyx_2);
  __pyx_2 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":44
 *     cdef BlockMap m
 *     m = BlockMap(16,4)
 *     for i from 0 <= i < 1000:             # <<<<<<<<<<<<<< 
 *         m.owner(3)
 * 
 */
  for (__pyx_3 = 0; __pyx_3 < 1000; __pyx_3++) {
    __pyx_1 = PyInt_FromLong(__pyx_3); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_1;
    __pyx_1 = 0;

    /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":45
 *     m = BlockMap(16,4)
 *     for i from 0 <= i < 1000:
 *         m.owner(3)             # <<<<<<<<<<<<<< 
 * 
 * def test3():
 */
    __pyx_2 = PyObject_GetAttr(((PyObject *)__pyx_v_m), __pyx_n_owner); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    Py_INCREF(__pyx_num_3);
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_num_3);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("maps_fast.test2");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF((PyObject *)__pyx_v_m);
  Py_DECREF(__pyx_v_i);
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":47
 *         m.owner(3)
 * 
 * def test3():             # <<<<<<<<<<<<<< 
 *     cdef BlockMap m
 *     m = BlockMap(16,4)
 */

static PyObject *__pyx_pf_9maps_fast_test3(PyObject *__pyx_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_9maps_fast_test3(PyObject *__pyx_self, PyObject *unused) {
  struct BlockMapObj *__pyx_v_m;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  long __pyx_3;
  __pyx_v_m = ((struct BlockMapObj *)Py_None); Py_INCREF(Py_None);
  __pyx_v_i = Py_None; Py_INCREF(Py_None);

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":49
 * def test3():
 *     cdef BlockMap m
 *     m = BlockMap(16,4)             # <<<<<<<<<<<<<< 
 *     for i from 0 <= i < 1000:
 *         m.c_owner(3)
 */
  __pyx_1 = PyTuple_New(2); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  Py_INCREF(__pyx_num_16);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_num_16);
  Py_INCREF(__pyx_num_4);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_num_4);
  __pyx_2 = PyObject_CallObject(((PyObject*)__pyx_ptype_9maps_fast_BlockMap), __pyx_1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (!__Pyx_TypeTest(__pyx_2, __pyx_ptype_9maps_fast_BlockMap)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_m));
  __pyx_v_m = ((struct BlockMapObj *)__pyx_2);
  __pyx_2 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":50
 *     cdef BlockMap m
 *     m = BlockMap(16,4)
 *     for i from 0 <= i < 1000:             # <<<<<<<<<<<<<< 
 *         m.c_owner(3)
 * 
 */
  for (__pyx_3 = 0; __pyx_3 < 1000; __pyx_3++) {
    __pyx_1 = PyInt_FromLong(__pyx_3); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_1;
    __pyx_1 = 0;

    /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":51
 *     m = BlockMap(16,4)
 *     for i from 0 <= i < 1000:
 *         m.c_owner(3)             # <<<<<<<<<<<<<< 
 * 
 * cdef public foo(int i):
 */
    ((struct __pyx_vtabstruct_9maps_fast_BlockMap *)__pyx_v_m->__pyx_vtab)->c_owner(__pyx_v_m,3);
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("maps_fast.test3");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF((PyObject *)__pyx_v_m);
  Py_DECREF(__pyx_v_i);
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":53
 *         m.c_owner(3)
 * 
 * cdef public foo(int i):             # <<<<<<<<<<<<<< 
 *     return i
 * 
 */

__PYX_EXTERN_C  DL_EXPORT(PyObject) *foo(int __pyx_v_i) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":54
 * 
 * cdef public foo(int i):
 *     return i             # <<<<<<<<<<<<<< 
 * 
 * 
 */
  __pyx_1 = PyInt_FromLong(__pyx_v_i); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("maps_fast.foo");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n___init__, "__init__"},
  {&__pyx_n_owner, "owner"},
  {0, 0}
};

static PyObject *__pyx_tp_new_9maps_fast_Map(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  return o;
}

static void __pyx_tp_dealloc_9maps_fast_Map(PyObject *o) {
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_9maps_fast_Map(PyObject *o, visitproc v, void *a) {
  return 0;
}

static int __pyx_tp_clear_9maps_fast_Map(PyObject *o) {
  return 0;
}

static struct PyMethodDef __pyx_methods_9maps_fast_Map[] = {
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Map = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_Map = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Map = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Map = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

DL_EXPORT(PyTypeObject) MapType = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "maps_fast.Map", /*tp_name*/
  sizeof(struct MapObj), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9maps_fast_Map, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Map, /*tp_as_number*/
  &__pyx_tp_as_sequence_Map, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Map, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Map, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_9maps_fast_Map, /*tp_traverse*/
  __pyx_tp_clear_9maps_fast_Map, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9maps_fast_Map, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_pf_9maps_fast_3Map___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9maps_fast_Map, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};
static struct __pyx_vtabstruct_9maps_fast_BlockMap __pyx_vtable_9maps_fast_BlockMap;

static PyObject *__pyx_tp_new_9maps_fast_BlockMap(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct BlockMapObj *p;
  PyObject *o = __pyx_ptype_9maps_fast_Map->tp_new(t, a, k);
  if (!o) return 0;
  p = ((struct BlockMapObj *)o);
  *(struct __pyx_vtabstruct_9maps_fast_BlockMap **)&p->__pyx_vtab = __pyx_vtabptr_9maps_fast_BlockMap;
  return o;
}

static void __pyx_tp_dealloc_9maps_fast_BlockMap(PyObject *o) {
  __pyx_ptype_9maps_fast_Map->tp_dealloc(o);
}

static int __pyx_tp_traverse_9maps_fast_BlockMap(PyObject *o, visitproc v, void *a) {
  int e;
  e = __pyx_ptype_9maps_fast_Map->tp_traverse(o, v, a); if (e) return e;
  return 0;
}

static int __pyx_tp_clear_9maps_fast_BlockMap(PyObject *o) {
  __pyx_ptype_9maps_fast_Map->tp_clear(o);
  return 0;
}

static struct PyMethodDef __pyx_methods_9maps_fast_BlockMap[] = {
  {"owner", (PyCFunction)__pyx_pf_9maps_fast_8BlockMap_owner, METH_O, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_BlockMap = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_BlockMap = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_BlockMap = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_BlockMap = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

DL_EXPORT(PyTypeObject) BlockMapType = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "maps_fast.BlockMap", /*tp_name*/
  sizeof(struct BlockMapObj), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9maps_fast_BlockMap, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_BlockMap, /*tp_as_number*/
  &__pyx_tp_as_sequence_BlockMap, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_BlockMap, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_BlockMap, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_9maps_fast_BlockMap, /*tp_traverse*/
  __pyx_tp_clear_9maps_fast_BlockMap, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9maps_fast_BlockMap, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9maps_fast_BlockMap, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"test1", (PyCFunction)__pyx_pf_9maps_fast_test1, METH_NOARGS, 0},
  {"test2", (PyCFunction)__pyx_pf_9maps_fast_test2, METH_NOARGS, 0},
  {"test3", (PyCFunction)__pyx_pf_9maps_fast_test3, METH_NOARGS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initmaps_fast(void); /*proto*/
PyMODINIT_FUNC initmaps_fast(void) {
  /*--- Libary function declarations ---*/
  __pyx_init_filenames();
  /*--- Module creation code ---*/
  __pyx_m = Py_InitModule4("maps_fast", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  /*--- Intern code ---*/
  __pyx_num_16 = PyInt_FromLong(16); if (unlikely(!__pyx_num_16)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_num_4 = PyInt_FromLong(4); if (unlikely(!__pyx_num_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_num_3 = PyInt_FromLong(3); if (unlikely(!__pyx_num_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  /*--- String init code ---*/
  /*--- Builtin init code ---*/
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Function import code ---*/
  /*--- Type init code ---*/
  if (PyType_Ready(&MapType) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Map", (PyObject *)&MapType) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;}
  __pyx_ptype_9maps_fast_Map = &MapType;
  __pyx_vtabptr_9maps_fast_BlockMap = &__pyx_vtable_9maps_fast_BlockMap;
  *(void(**)(void))&__pyx_vtable_9maps_fast_BlockMap.c_owner = (void(*)(void))__pyx_f_9maps_fast_8BlockMap_c_owner;
  *(void(**)(void))&__pyx_vtable_9maps_fast_BlockMap.local_index = (void(*)(void))__pyx_f_9maps_fast_8BlockMap_local_index;
  *(void(**)(void))&__pyx_vtable_9maps_fast_BlockMap.global_index = (void(*)(void))__pyx_f_9maps_fast_8BlockMap_global_index;
  BlockMapType.tp_base = __pyx_ptype_9maps_fast_Map;
  if (PyType_Ready(&BlockMapType) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  if (__Pyx_SetVtable(BlockMapType.tp_dict, __pyx_vtabptr_9maps_fast_BlockMap) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "BlockMap", (PyObject *)&BlockMapType) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  __pyx_ptype_9maps_fast_BlockMap = &BlockMapType;
  /*--- Type import code ---*/
  /*--- Execution code ---*/

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/maps_fast.pyx":53
 *         m.c_owner(3)
 * 
 * cdef public foo(int i):             # <<<<<<<<<<<<<< 
 *     return i
 * 
 */
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("maps_fast");
}

static char *__pyx_filenames[] = {
  "maps_fast.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetStdout(void) {
    PyObject *f = PySys_GetObject("stdout");
    if (!f) {
        PyErr_SetString(PyExc_RuntimeError, "lost sys.stdout");
    }
    return f;
}

static int __Pyx_PrintItem(PyObject *v) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_SoftSpace(f, 1)) {
        if (PyFile_WriteString(" ", f) < 0)
            return -1;
    }
    if (PyFile_WriteObject(v, f, Py_PRINT_RAW) < 0)
        return -1;
    if (PyString_Check(v)) {
        char *s = PyString_AsString(v);
        Py_ssize_t len = PyString_Size(v);
        if (len > 0 &&
            isspace(Py_CHARMASK(s[len-1])) &&
            s[len-1] != ' ')
                PyFile_SoftSpace(f, 0);
    }
    return 0;
}

static int __Pyx_PrintNewline(void) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_WriteString("\n", f) < 0)
        return -1;
    PyFile_SoftSpace(f, 0);
    return 0;
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        obj->ob_type->tp_name, type->tp_name);
    return 0;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        PY_LONG_LONG val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        PY_LONG_LONG val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}
