/* Generated by Cython 0.9.6.13.1 on Mon Apr 28 14:06:05 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#ifndef __stdcall
  #define __stdcall
#endif
#ifndef __cdecl
  #define __cdecl
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n; int is_unicode;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static char * __pyx_cfilenm= __FILE__;
static char *__pyx_filename;
static char **__pyx_f;

static INLINE void __Pyx_RaiseArgtupleTooLong(Py_ssize_t num_expected, Py_ssize_t num_found); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static void __Pyx_WriteUnraisable(char *name); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static int __Pyx_ExportFunction(char *n, void *f, char *s); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations */

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pxd":1
 * cdef class Map:             # <<<<<<<<<<<<<< 
 *     cdef public int shape
 *     cdef public int grid_shape
 */

struct __pyx_obj_9maps_fast_Map {
  PyObject_HEAD
  struct __pyx_vtabstruct_9maps_fast_Map *__pyx_vtab;
  int shape;
  int grid_shape;
  int local_shape;
};

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pxd":9
 *     cdef int global_index_c(self, int owner, int p)
 * 
 * cdef class BlockMap(Map):             # <<<<<<<<<<<<<< 
 *     pass
 * 
 */

struct __pyx_obj_9maps_fast_BlockMap {
  struct __pyx_obj_9maps_fast_Map __pyx_base;
};

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pxd":12
 *     pass
 * 
 * cdef class CyclicMap(Map):             # <<<<<<<<<<<<<< 
 *     pass
 * 
 */

struct __pyx_obj_9maps_fast_CyclicMap {
  struct __pyx_obj_9maps_fast_Map __pyx_base;
};

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pxd":15
 *     pass
 * 
 * cdef class BlockCyclicMap(Map):             # <<<<<<<<<<<<<< 
 *     pass
 * 
 */

struct __pyx_obj_9maps_fast_BlockCyclicMap {
  struct __pyx_obj_9maps_fast_Map __pyx_base;
};


/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":7
 * from ipythondistarray.core.error import InvalidMapCode
 * 
 * cdef class Map:             # <<<<<<<<<<<<<< 
 * 
 *     def __init__(self, shape, grid_shape):
 */

struct __pyx_vtabstruct_9maps_fast_Map {
  int (*owner_c)(struct __pyx_obj_9maps_fast_Map *, int);
  int (*local_index_c)(struct __pyx_obj_9maps_fast_Map *, int);
  int (*global_index_c)(struct __pyx_obj_9maps_fast_Map *, int, int);
};
static struct __pyx_vtabstruct_9maps_fast_Map *__pyx_vtabptr_9maps_fast_Map;


/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":58
 *         return owner + p*self.grid_shape
 * 
 * cdef class BlockCyclicMap(Map):             # <<<<<<<<<<<<<< 
 *     pass
 * 
 */

struct __pyx_vtabstruct_9maps_fast_BlockCyclicMap {
  struct __pyx_vtabstruct_9maps_fast_Map __pyx_base;
};
static struct __pyx_vtabstruct_9maps_fast_BlockCyclicMap *__pyx_vtabptr_9maps_fast_BlockCyclicMap;


/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":35
 * 
 * 
 * cdef class BlockMap(Map):             # <<<<<<<<<<<<<< 
 *     
 *     cdef int owner_c(self, int i):
 */

struct __pyx_vtabstruct_9maps_fast_BlockMap {
  struct __pyx_vtabstruct_9maps_fast_Map __pyx_base;
};
static struct __pyx_vtabstruct_9maps_fast_BlockMap *__pyx_vtabptr_9maps_fast_BlockMap;


/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":47
 * 
 * 
 * cdef class CyclicMap(Map):             # <<<<<<<<<<<<<< 
 *     
 *     cdef int owner_c(self, int i):
 */

struct __pyx_vtabstruct_9maps_fast_CyclicMap {
  struct __pyx_vtabstruct_9maps_fast_Map __pyx_base;
};
static struct __pyx_vtabstruct_9maps_fast_CyclicMap *__pyx_vtabptr_9maps_fast_CyclicMap;

static PyTypeObject *__pyx_ptype_9maps_fast_Map = 0;
static PyTypeObject *__pyx_ptype_9maps_fast_BlockMap = 0;
static PyTypeObject *__pyx_ptype_9maps_fast_CyclicMap = 0;
static PyTypeObject *__pyx_ptype_9maps_fast_BlockCyclicMap = 0;


/* Implementation of maps_fast */

static char __pyx_k_2[] = "ipythondistarray.core.error";

static PyObject *__pyx_n___init__;
static PyObject *__pyx_n_owner;
static PyObject *__pyx_n_local_index;
static PyObject *__pyx_n_global_index;
static PyObject *__pyx_n_inspect;
static PyObject *__pyx_n_InvalidMapCode;
static PyObject *__pyx_n_MapRegistry;
static PyObject *__pyx_n_object;
static PyObject *__pyx_n_register_map;
static PyObject *__pyx_n_get_map_class;
static PyObject *__pyx_n__map_registry;
static PyObject *__pyx_n_b;
static PyObject *__pyx_n_c;
static PyObject *__pyx_n_bc;

static PyObject *__pyx_k_2p;

static PyObject *__pyx_builtin_object;

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":9
 * cdef class Map:
 * 
 *     def __init__(self, shape, grid_shape):             # <<<<<<<<<<<<<< 
 *         self.shape = shape
 *         self.grid_shape = grid_shape
 */

static int __pyx_pf_9maps_fast_3Map___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_pf_9maps_fast_3Map___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_shape = 0;
  PyObject *__pyx_v_grid_shape = 0;
  int __pyx_r;
  int __pyx_1;
  int __pyx_2;
  static char *__pyx_argnames[] = {"shape","grid_shape",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_shape = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_grid_shape = PyTuple_GET_ITEM(__pyx_args, 1);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_shape, &__pyx_v_grid_shape))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("maps_fast.Map.__init__");
  return -1;
  __pyx_L3:;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":10
 * 
 *     def __init__(self, shape, grid_shape):
 *         self.shape = shape             # <<<<<<<<<<<<<< 
 *         self.grid_shape = grid_shape
 *         self.local_shape = self.shape/self.grid_shape
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_shape); if (unlikely((__pyx_1 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; __pyx_clineno = __LINE__; goto __pyx_L1;}
  ((struct __pyx_obj_9maps_fast_Map *)__pyx_v_self)->shape = __pyx_1;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":11
 *     def __init__(self, shape, grid_shape):
 *         self.shape = shape
 *         self.grid_shape = grid_shape             # <<<<<<<<<<<<<< 
 *         self.local_shape = self.shape/self.grid_shape
 *         if self.shape%self.grid_shape > 0:
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_grid_shape); if (unlikely((__pyx_1 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; __pyx_clineno = __LINE__; goto __pyx_L1;}
  ((struct __pyx_obj_9maps_fast_Map *)__pyx_v_self)->grid_shape = __pyx_1;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":12
 *         self.shape = shape
 *         self.grid_shape = grid_shape
 *         self.local_shape = self.shape/self.grid_shape             # <<<<<<<<<<<<<< 
 *         if self.shape%self.grid_shape > 0:
 *             self.local_shape += 1
 */
  ((struct __pyx_obj_9maps_fast_Map *)__pyx_v_self)->local_shape = (((struct __pyx_obj_9maps_fast_Map *)__pyx_v_self)->shape / ((struct __pyx_obj_9maps_fast_Map *)__pyx_v_self)->grid_shape);

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":13
 *         self.grid_shape = grid_shape
 *         self.local_shape = self.shape/self.grid_shape
 *         if self.shape%self.grid_shape > 0:             # <<<<<<<<<<<<<< 
 *             self.local_shape += 1
 *     
 */
  __pyx_2 = ((((struct __pyx_obj_9maps_fast_Map *)__pyx_v_self)->shape % ((struct __pyx_obj_9maps_fast_Map *)__pyx_v_self)->grid_shape) > 0);
  if (__pyx_2) {

    /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":14
 *         self.local_shape = self.shape/self.grid_shape
 *         if self.shape%self.grid_shape > 0:
 *             self.local_shape += 1             # <<<<<<<<<<<<<< 
 *     
 *     cdef int owner_c(self, int i):
 */
    ((struct __pyx_obj_9maps_fast_Map *)__pyx_v_self)->local_shape += 1;
    goto __pyx_L4;
  }
  __pyx_L4:;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("maps_fast.Map.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":16
 *             self.local_shape += 1
 *     
 *     cdef int owner_c(self, int i):             # <<<<<<<<<<<<<< 
 *         raise NotImplementedError("this method needs to be implemented in a subclass")
 *     
 */

static PyObject *__pyx_n_NotImplementedError;

static PyObject *__pyx_k_8p;

static PyObject *__pyx_builtin_NotImplementedError;

static char __pyx_k_8[] = "this method needs to be implemented in a subclass";

static  int __pyx_f_9maps_fast_3Map_owner_c(struct __pyx_obj_9maps_fast_Map *__pyx_v_self, int __pyx_v_i) {
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":17
 *     
 *     cdef int owner_c(self, int i):
 *         raise NotImplementedError("this method needs to be implemented in a subclass")             # <<<<<<<<<<<<<< 
 *     
 *     cdef int local_index_c(self, int i):
 */
  __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_k_8p);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_k_8p);
  __pyx_2 = PyObject_Call(__pyx_builtin_NotImplementedError, __pyx_1, NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __Pyx_Raise(__pyx_2, 0, 0);
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; __pyx_clineno = __LINE__; goto __pyx_L1;}

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_WriteUnraisable("maps_fast.Map.owner_c");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":19
 *         raise NotImplementedError("this method needs to be implemented in a subclass")
 *     
 *     cdef int local_index_c(self, int i):             # <<<<<<<<<<<<<< 
 *         raise NotImplementedError("this method needs to be implemented in a subclass")
 *     
 */

static PyObject *__pyx_k_9p;

static char __pyx_k_9[] = "this method needs to be implemented in a subclass";

static  int __pyx_f_9maps_fast_3Map_local_index_c(struct __pyx_obj_9maps_fast_Map *__pyx_v_self, int __pyx_v_i) {
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":20
 *     
 *     cdef int local_index_c(self, int i):
 *         raise NotImplementedError("this method needs to be implemented in a subclass")             # <<<<<<<<<<<<<< 
 *     
 *     cdef int global_index_c(self, int owner, int p):
 */
  __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_k_9p);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_k_9p);
  __pyx_2 = PyObject_Call(__pyx_builtin_NotImplementedError, __pyx_1, NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __Pyx_Raise(__pyx_2, 0, 0);
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_WriteUnraisable("maps_fast.Map.local_index_c");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":22
 *         raise NotImplementedError("this method needs to be implemented in a subclass")
 *     
 *     cdef int global_index_c(self, int owner, int p):             # <<<<<<<<<<<<<< 
 *         raise NotImplementedError("this method needs to be implemented in a subclass")
 *     
 */

static PyObject *__pyx_k_10p;

static char __pyx_k_10[] = "this method needs to be implemented in a subclass";

static  int __pyx_f_9maps_fast_3Map_global_index_c(struct __pyx_obj_9maps_fast_Map *__pyx_v_self, int __pyx_v_owner, int __pyx_v_p) {
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":23
 *     
 *     cdef int global_index_c(self, int owner, int p):
 *         raise NotImplementedError("this method needs to be implemented in a subclass")             # <<<<<<<<<<<<<< 
 *     
 *     def owner(self, i):
 */
  __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_k_10p);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_k_10p);
  __pyx_2 = PyObject_Call(__pyx_builtin_NotImplementedError, __pyx_1, NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __Pyx_Raise(__pyx_2, 0, 0);
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L1;}

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_WriteUnraisable("maps_fast.Map.global_index_c");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":25
 *         raise NotImplementedError("this method needs to be implemented in a subclass")
 *     
 *     def owner(self, i):             # <<<<<<<<<<<<<< 
 *         return self.owner_c(i)
 *     
 */

static PyObject *__pyx_pf_9maps_fast_3Map_owner(PyObject *__pyx_v_self, PyObject *__pyx_v_i); /*proto*/
static PyObject *__pyx_pf_9maps_fast_3Map_owner(PyObject *__pyx_v_self, PyObject *__pyx_v_i) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":26
 *     
 *     def owner(self, i):
 *         return self.owner_c(i)             # <<<<<<<<<<<<<< 
 *     
 *     def local_index(self, i):
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_i); if (unlikely((__pyx_1 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(((struct __pyx_vtabstruct_9maps_fast_Map *)((struct __pyx_obj_9maps_fast_Map *)__pyx_v_self)->__pyx_vtab)->owner_c(((struct __pyx_obj_9maps_fast_Map *)__pyx_v_self), __pyx_1)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("maps_fast.Map.owner");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":28
 *         return self.owner_c(i)
 *     
 *     def local_index(self, i):             # <<<<<<<<<<<<<< 
 *         return self.local_index_c(i)
 *     
 */

static PyObject *__pyx_pf_9maps_fast_3Map_local_index(PyObject *__pyx_v_self, PyObject *__pyx_v_i); /*proto*/
static PyObject *__pyx_pf_9maps_fast_3Map_local_index(PyObject *__pyx_v_self, PyObject *__pyx_v_i) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":29
 *     
 *     def local_index(self, i):
 *         return self.local_index_c(i)             # <<<<<<<<<<<<<< 
 *     
 *     def global_index(self, owner, p):
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_i); if (unlikely((__pyx_1 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(((struct __pyx_vtabstruct_9maps_fast_Map *)((struct __pyx_obj_9maps_fast_Map *)__pyx_v_self)->__pyx_vtab)->local_index_c(((struct __pyx_obj_9maps_fast_Map *)__pyx_v_self), __pyx_1)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("maps_fast.Map.local_index");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":31
 *         return self.local_index_c(i)
 *     
 *     def global_index(self, owner, p):             # <<<<<<<<<<<<<< 
 *         return self.global_index_c(owner, p)
 * 
 */

static PyObject *__pyx_pf_9maps_fast_3Map_global_index(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_9maps_fast_3Map_global_index(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_owner = 0;
  PyObject *__pyx_v_p = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"owner","p",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_owner = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_p = PyTuple_GET_ITEM(__pyx_args, 1);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_owner, &__pyx_v_p))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("maps_fast.Map.global_index");
  return NULL;
  __pyx_L3:;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":32
 *     
 *     def global_index(self, owner, p):
 *         return self.global_index_c(owner, p)             # <<<<<<<<<<<<<< 
 * 
 * 
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_owner); if (unlikely((__pyx_1 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = __pyx_PyInt_int(__pyx_v_p); if (unlikely((__pyx_2 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(((struct __pyx_vtabstruct_9maps_fast_Map *)((struct __pyx_obj_9maps_fast_Map *)__pyx_v_self)->__pyx_vtab)->global_index_c(((struct __pyx_obj_9maps_fast_Map *)__pyx_v_self), __pyx_1, __pyx_2)); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("maps_fast.Map.global_index");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":37
 * cdef class BlockMap(Map):
 *     
 *     cdef int owner_c(self, int i):             # <<<<<<<<<<<<<< 
 *         return i/self.local_shape
 *     
 */

static  int __pyx_f_9maps_fast_8BlockMap_owner_c(struct __pyx_obj_9maps_fast_BlockMap *__pyx_v_self, int __pyx_v_i) {
  int __pyx_r;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":38
 *     
 *     cdef int owner_c(self, int i):
 *         return i/self.local_shape             # <<<<<<<<<<<<<< 
 *     
 *     cdef int local_index_c(self, int i):
 */
  __pyx_r = (__pyx_v_i / __pyx_v_self->__pyx_base.local_shape);
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":40
 *         return i/self.local_shape
 *     
 *     cdef int local_index_c(self, int i):             # <<<<<<<<<<<<<< 
 *         return i%self.local_shape
 *     
 */

static  int __pyx_f_9maps_fast_8BlockMap_local_index_c(struct __pyx_obj_9maps_fast_BlockMap *__pyx_v_self, int __pyx_v_i) {
  int __pyx_r;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":41
 *     
 *     cdef int local_index_c(self, int i):
 *         return i%self.local_shape             # <<<<<<<<<<<<<< 
 *     
 *     cdef int global_index_c(self, int owner, int p):
 */
  __pyx_r = (__pyx_v_i % __pyx_v_self->__pyx_base.local_shape);
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":43
 *         return i%self.local_shape
 *     
 *     cdef int global_index_c(self, int owner, int p):             # <<<<<<<<<<<<<< 
 *         return owner*self.local_shape + p
 * 
 */

static  int __pyx_f_9maps_fast_8BlockMap_global_index_c(struct __pyx_obj_9maps_fast_BlockMap *__pyx_v_self, int __pyx_v_owner, int __pyx_v_p) {
  int __pyx_r;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":44
 *     
 *     cdef int global_index_c(self, int owner, int p):
 *         return owner*self.local_shape + p             # <<<<<<<<<<<<<< 
 * 
 * 
 */
  __pyx_r = ((__pyx_v_owner * __pyx_v_self->__pyx_base.local_shape) + __pyx_v_p);
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":49
 * cdef class CyclicMap(Map):
 *     
 *     cdef int owner_c(self, int i):             # <<<<<<<<<<<<<< 
 *         return i%self.grid_shape
 *     
 */

static  int __pyx_f_9maps_fast_9CyclicMap_owner_c(struct __pyx_obj_9maps_fast_CyclicMap *__pyx_v_self, int __pyx_v_i) {
  int __pyx_r;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":50
 *     
 *     cdef int owner_c(self, int i):
 *         return i%self.grid_shape             # <<<<<<<<<<<<<< 
 *     
 *     cdef int local_index_c(self, int i):
 */
  __pyx_r = (__pyx_v_i % __pyx_v_self->__pyx_base.grid_shape);
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":52
 *         return i%self.grid_shape
 *     
 *     cdef int local_index_c(self, int i):             # <<<<<<<<<<<<<< 
 *         return i/self.grid_shape
 * 
 */

static  int __pyx_f_9maps_fast_9CyclicMap_local_index_c(struct __pyx_obj_9maps_fast_CyclicMap *__pyx_v_self, int __pyx_v_i) {
  int __pyx_r;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":53
 *     
 *     cdef int local_index_c(self, int i):
 *         return i/self.grid_shape             # <<<<<<<<<<<<<< 
 * 
 *     cdef int global_index_c(self, int owner, int p):
 */
  __pyx_r = (__pyx_v_i / __pyx_v_self->__pyx_base.grid_shape);
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":55
 *         return i/self.grid_shape
 * 
 *     cdef int global_index_c(self, int owner, int p):             # <<<<<<<<<<<<<< 
 *         return owner + p*self.grid_shape
 * 
 */

static  int __pyx_f_9maps_fast_9CyclicMap_global_index_c(struct __pyx_obj_9maps_fast_CyclicMap *__pyx_v_self, int __pyx_v_owner, int __pyx_v_p) {
  int __pyx_r;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":56
 * 
 *     cdef int global_index_c(self, int owner, int p):
 *         return owner + p*self.grid_shape             # <<<<<<<<<<<<<< 
 * 
 * cdef class BlockCyclicMap(Map):
 */
  __pyx_r = (__pyx_v_owner + (__pyx_v_p * __pyx_v_self->__pyx_base.grid_shape));
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":63
 * class MapRegistry(object):
 *     
 *     def __init__(self):             # <<<<<<<<<<<<<< 
 *         self.maps = {}
 *         
 */

static PyObject *__pyx_n_maps;

static PyObject *__pyx_pf_9maps_fast_11MapRegistry___init__(PyObject *__pyx_self, PyObject *__pyx_v_self); /*proto*/
static PyMethodDef __pyx_mdef_9maps_fast_11MapRegistry___init__ = {"__init__", (PyCFunction)__pyx_pf_9maps_fast_11MapRegistry___init__, METH_O, 0};
static PyObject *__pyx_pf_9maps_fast_11MapRegistry___init__(PyObject *__pyx_self, PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  __pyx_1 = PyDict_New(); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; __pyx_clineno = __LINE__; goto __pyx_L1;}

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":64
 *     
 *     def __init__(self):
 *         self.maps = {}             # <<<<<<<<<<<<<< 
 *         
 *     def register_map(self, code, m):
 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_maps, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("maps_fast.MapRegistry.__init__");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":66
 *         self.maps = {}
 *         
 *     def register_map(self, code, m):             # <<<<<<<<<<<<<< 
 *         if inspect.isclass(m):
 *             if issubclass(m, Map):
 */

static PyObject *__pyx_n_isclass;
static PyObject *__pyx_n_TypeError;

static PyObject *__pyx_k_11p;
static PyObject *__pyx_k_12p;

static PyObject *__pyx_builtin_TypeError;

static char __pyx_k_11[] = "Must register a Map subclass.";
static char __pyx_k_12[] = "Must register a class";

static PyObject *__pyx_pf_9maps_fast_11MapRegistry_register_map(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_9maps_fast_11MapRegistry_register_map = {"register_map", (PyCFunction)__pyx_pf_9maps_fast_11MapRegistry_register_map, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_pf_9maps_fast_11MapRegistry_register_map(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_code = 0;
  PyObject *__pyx_v_m = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  static char *__pyx_argnames[] = {"self","code","m",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 3)) {
    __pyx_v_self = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_code = PyTuple_GET_ITEM(__pyx_args, 1);
    __pyx_v_m = PyTuple_GET_ITEM(__pyx_args, 2);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_self, &__pyx_v_code, &__pyx_v_m))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("maps_fast.MapRegistry.register_map");
  return NULL;
  __pyx_L3:;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":67
 *         
 *     def register_map(self, code, m):
 *         if inspect.isclass(m):             # <<<<<<<<<<<<<< 
 *             if issubclass(m, Map):
 *                 self.maps[code] = m
 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_inspect); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_isclass); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_m);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_m);
  __pyx_3 = PyObject_Call(__pyx_2, __pyx_1, NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_4 = __Pyx_PyObject_IsTrue(__pyx_3); if (unlikely(__pyx_4 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__pyx_4) {

    /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":68
 *     def register_map(self, code, m):
 *         if inspect.isclass(m):
 *             if issubclass(m, Map):             # <<<<<<<<<<<<<< 
 *                 self.maps[code] = m
 *             else:
 */
    __pyx_4 = PyObject_IsSubclass(__pyx_v_m, ((PyObject*)__pyx_ptype_9maps_fast_Map)); if (unlikely(__pyx_4 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1;}
    if (__pyx_4) {

      /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":69
 *         if inspect.isclass(m):
 *             if issubclass(m, Map):
 *                 self.maps[code] = m             # <<<<<<<<<<<<<< 
 *             else:
 *                 raise TypeError("Must register a Map subclass.")
 */
      __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_maps); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; __pyx_clineno = __LINE__; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_2, __pyx_v_code, __pyx_v_m) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      goto __pyx_L5;
    }
    /*else*/ {

      /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":71
 *                 self.maps[code] = m
 *             else:
 *                 raise TypeError("Must register a Map subclass.")             # <<<<<<<<<<<<<< 
 *         else:
 *             raise TypeError("Must register a class")
 */
      __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_INCREF(__pyx_k_11p);
      PyTuple_SET_ITEM(__pyx_1, 0, __pyx_k_11p);
      __pyx_3 = PyObject_Call(__pyx_builtin_TypeError, __pyx_1, NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      __Pyx_Raise(__pyx_3, 0, 0);
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
    }
    __pyx_L5:;
    goto __pyx_L4;
  }
  /*else*/ {

    /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":73
 *                 raise TypeError("Must register a Map subclass.")
 *         else:
 *             raise TypeError("Must register a class")             # <<<<<<<<<<<<<< 
 * 
 *     def get_map_class(self, code):
 */
    __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_INCREF(__pyx_k_12p);
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_k_12p);
    __pyx_1 = PyObject_Call(__pyx_builtin_TypeError, __pyx_2, NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __Pyx_Raise(__pyx_1, 0, 0);
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1;}
  }
  __pyx_L4:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("maps_fast.MapRegistry.register_map");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":75
 *             raise TypeError("Must register a class")
 * 
 *     def get_map_class(self, code):             # <<<<<<<<<<<<<< 
 *         m = self.maps.get(code)
 *         if m is None:
 */

static PyObject *__pyx_n_get;

static PyObject *__pyx_k_13p;
static PyObject *__pyx_k_14p;

static char __pyx_k_13[] = "Not a Map subclass or a valid map code: %s";
static char __pyx_k_14[] = "Not a Map subclass or a valid map code: %s";

static PyObject *__pyx_pf_9maps_fast_11MapRegistry_get_map_class(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_9maps_fast_11MapRegistry_get_map_class = {"get_map_class", (PyCFunction)__pyx_pf_9maps_fast_11MapRegistry_get_map_class, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_pf_9maps_fast_11MapRegistry_get_map_class(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_code = 0;
  PyObject *__pyx_v_m;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  static char *__pyx_argnames[] = {"self","code",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_self = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_code = PyTuple_GET_ITEM(__pyx_args, 1);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_self, &__pyx_v_code))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("maps_fast.MapRegistry.get_map_class");
  return NULL;
  __pyx_L3:;
  __pyx_v_m = Py_None; Py_INCREF(Py_None);

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":76
 * 
 *     def get_map_class(self, code):
 *         m = self.maps.get(code)             # <<<<<<<<<<<<<< 
 *         if m is None:
 *             if inspect.isclass(code): 
 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_maps); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_get); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_code);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_code);
  __pyx_3 = PyObject_Call(__pyx_2, __pyx_1, NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_m);
  __pyx_v_m = __pyx_3;
  __pyx_3 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":77
 *     def get_map_class(self, code):
 *         m = self.maps.get(code)
 *         if m is None:             # <<<<<<<<<<<<<< 
 *             if inspect.isclass(code): 
 *                 if issubclass(code, Map):
 */
  __pyx_4 = (__pyx_v_m == Py_None);
  if (__pyx_4) {

    /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":78
 *         m = self.maps.get(code)
 *         if m is None:
 *             if inspect.isclass(code):             # <<<<<<<<<<<<<< 
 *                 if issubclass(code, Map):
 *                     return code
 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_inspect); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; __pyx_clineno = __LINE__; goto __pyx_L1;}
    __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_isclass); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_INCREF(__pyx_v_code);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_code);
    __pyx_2 = PyObject_Call(__pyx_1, __pyx_3, NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_4 = __Pyx_PyObject_IsTrue(__pyx_2); if (unlikely(__pyx_4 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (__pyx_4) {

      /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":79
 *         if m is None:
 *             if inspect.isclass(code): 
 *                 if issubclass(code, Map):             # <<<<<<<<<<<<<< 
 *                     return code
 *                 else:
 */
      __pyx_4 = PyObject_IsSubclass(__pyx_v_code, ((PyObject*)__pyx_ptype_9maps_fast_Map)); if (unlikely(__pyx_4 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; __pyx_clineno = __LINE__; goto __pyx_L1;}
      if (__pyx_4) {

        /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":80
 *             if inspect.isclass(code): 
 *                 if issubclass(code, Map):
 *                     return code             # <<<<<<<<<<<<<< 
 *                 else:
 *                     raise InvalidMapCode("Not a Map subclass or a valid map code: %s"%code)
 */
        Py_INCREF(__pyx_v_code);
        __pyx_r = __pyx_v_code;
        goto __pyx_L0;
        goto __pyx_L6;
      }
      /*else*/ {

        /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":82
 *                     return code
 *                 else:
 *                     raise InvalidMapCode("Not a Map subclass or a valid map code: %s"%code)             # <<<<<<<<<<<<<< 
 *             else:
 *                 raise InvalidMapCode("Not a Map subclass or a valid map code: %s"%code)
 */
        __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_InvalidMapCode); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L1;}
        __pyx_3 = PyNumber_Remainder(__pyx_k_13p, __pyx_v_code); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L1;}
        __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L1;}
        PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
        __pyx_3 = 0;
        __pyx_3 = PyObject_Call(__pyx_1, __pyx_2, NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L1;}
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        Py_DECREF(__pyx_2); __pyx_2 = 0;
        __Pyx_Raise(__pyx_3, 0, 0);
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L1;}
      }
      __pyx_L6:;
      goto __pyx_L5;
    }
    /*else*/ {

      /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":84
 *                     raise InvalidMapCode("Not a Map subclass or a valid map code: %s"%code)
 *             else:
 *                 raise InvalidMapCode("Not a Map subclass or a valid map code: %s"%code)             # <<<<<<<<<<<<<< 
 *         else:
 *             return m
 */
      __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_InvalidMapCode); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_2 = PyNumber_Remainder(__pyx_k_14p, __pyx_v_code); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; __pyx_clineno = __LINE__; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
      __pyx_2 = 0;
      __pyx_2 = PyObject_Call(__pyx_1, __pyx_3, NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __Pyx_Raise(__pyx_2, 0, 0);
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; __pyx_clineno = __LINE__; goto __pyx_L1;}
    }
    __pyx_L5:;
    goto __pyx_L4;
  }
  /*else*/ {

    /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":86
 *                 raise InvalidMapCode("Not a Map subclass or a valid map code: %s"%code)
 *         else:
 *             return m             # <<<<<<<<<<<<<< 
 *             
 *             
 */
    Py_INCREF(__pyx_v_m);
    __pyx_r = __pyx_v_m;
    goto __pyx_L0;
  }
  __pyx_L4:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("maps_fast.MapRegistry.get_map_class");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_m);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_InvalidMapCode, "InvalidMapCode"},
  {&__pyx_n_MapRegistry, "MapRegistry"},
  {&__pyx_n_NotImplementedError, "NotImplementedError"},
  {&__pyx_n_TypeError, "TypeError"},
  {&__pyx_n___init__, "__init__"},
  {&__pyx_n__map_registry, "_map_registry"},
  {&__pyx_n_b, "b"},
  {&__pyx_n_bc, "bc"},
  {&__pyx_n_c, "c"},
  {&__pyx_n_get, "get"},
  {&__pyx_n_get_map_class, "get_map_class"},
  {&__pyx_n_global_index, "global_index"},
  {&__pyx_n_inspect, "inspect"},
  {&__pyx_n_isclass, "isclass"},
  {&__pyx_n_local_index, "local_index"},
  {&__pyx_n_maps, "maps"},
  {&__pyx_n_object, "object"},
  {&__pyx_n_owner, "owner"},
  {&__pyx_n_register_map, "register_map"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k_2p, __pyx_k_2, sizeof(__pyx_k_2), 0},
  {&__pyx_k_8p, __pyx_k_8, sizeof(__pyx_k_8), 0},
  {&__pyx_k_9p, __pyx_k_9, sizeof(__pyx_k_9), 0},
  {&__pyx_k_10p, __pyx_k_10, sizeof(__pyx_k_10), 0},
  {&__pyx_k_11p, __pyx_k_11, sizeof(__pyx_k_11), 0},
  {&__pyx_k_12p, __pyx_k_12, sizeof(__pyx_k_12), 0},
  {&__pyx_k_13p, __pyx_k_13, sizeof(__pyx_k_13), 0},
  {&__pyx_k_14p, __pyx_k_14, sizeof(__pyx_k_14), 0},
  {0, 0, 0, 0}
};
static struct __pyx_vtabstruct_9maps_fast_Map __pyx_vtable_9maps_fast_Map;

static PyObject *__pyx_tp_new_9maps_fast_Map(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_9maps_fast_Map *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_9maps_fast_Map *)o);
  *(struct __pyx_vtabstruct_9maps_fast_Map **)&p->__pyx_vtab = __pyx_vtabptr_9maps_fast_Map;
  return o;
}

static void __pyx_tp_dealloc_9maps_fast_Map(PyObject *o) {
  (*o->ob_type->tp_free)(o);
}

static struct PyMethodDef __pyx_methods_9maps_fast_Map[] = {
  {"owner", (PyCFunction)__pyx_pf_9maps_fast_3Map_owner, METH_O, 0},
  {"local_index", (PyCFunction)__pyx_pf_9maps_fast_3Map_local_index, METH_O, 0},
  {"global_index", (PyCFunction)__pyx_pf_9maps_fast_3Map_global_index, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_9maps_fast_Map[] = {
  {"shape", T_INT, offsetof(struct __pyx_obj_9maps_fast_Map, shape), 0, 0},
  {"grid_shape", T_INT, offsetof(struct __pyx_obj_9maps_fast_Map, grid_shape), 0, 0},
  {"local_shape", T_INT, offsetof(struct __pyx_obj_9maps_fast_Map, local_shape), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Map = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_Map = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Map = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Map = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_9maps_fast_Map = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "maps_fast.Map", /*tp_name*/
  sizeof(struct __pyx_obj_9maps_fast_Map), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9maps_fast_Map, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Map, /*tp_as_number*/
  &__pyx_tp_as_sequence_Map, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Map, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Map, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9maps_fast_Map, /*tp_methods*/
  __pyx_members_9maps_fast_Map, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_pf_9maps_fast_3Map___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9maps_fast_Map, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};
static struct __pyx_vtabstruct_9maps_fast_BlockMap __pyx_vtable_9maps_fast_BlockMap;

static PyObject *__pyx_tp_new_9maps_fast_BlockMap(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_9maps_fast_BlockMap *p;
  PyObject *o = __pyx_tp_new_9maps_fast_Map(t, a, k);
  if (!o) return 0;
  p = ((struct __pyx_obj_9maps_fast_BlockMap *)o);
  *(struct __pyx_vtabstruct_9maps_fast_BlockMap **)&p->__pyx_base.__pyx_vtab = __pyx_vtabptr_9maps_fast_BlockMap;
  return o;
}

static struct PyMethodDef __pyx_methods_9maps_fast_BlockMap[] = {
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_BlockMap = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_BlockMap = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_BlockMap = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_BlockMap = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_9maps_fast_BlockMap = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "maps_fast.BlockMap", /*tp_name*/
  sizeof(struct __pyx_obj_9maps_fast_BlockMap), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9maps_fast_Map, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_BlockMap, /*tp_as_number*/
  &__pyx_tp_as_sequence_BlockMap, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_BlockMap, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_BlockMap, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9maps_fast_BlockMap, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9maps_fast_BlockMap, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};
static struct __pyx_vtabstruct_9maps_fast_CyclicMap __pyx_vtable_9maps_fast_CyclicMap;

static PyObject *__pyx_tp_new_9maps_fast_CyclicMap(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_9maps_fast_CyclicMap *p;
  PyObject *o = __pyx_tp_new_9maps_fast_Map(t, a, k);
  if (!o) return 0;
  p = ((struct __pyx_obj_9maps_fast_CyclicMap *)o);
  *(struct __pyx_vtabstruct_9maps_fast_CyclicMap **)&p->__pyx_base.__pyx_vtab = __pyx_vtabptr_9maps_fast_CyclicMap;
  return o;
}

static struct PyMethodDef __pyx_methods_9maps_fast_CyclicMap[] = {
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_CyclicMap = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_CyclicMap = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_CyclicMap = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_CyclicMap = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_9maps_fast_CyclicMap = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "maps_fast.CyclicMap", /*tp_name*/
  sizeof(struct __pyx_obj_9maps_fast_CyclicMap), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9maps_fast_Map, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_CyclicMap, /*tp_as_number*/
  &__pyx_tp_as_sequence_CyclicMap, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_CyclicMap, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_CyclicMap, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9maps_fast_CyclicMap, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9maps_fast_CyclicMap, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};
static struct __pyx_vtabstruct_9maps_fast_BlockCyclicMap __pyx_vtable_9maps_fast_BlockCyclicMap;

static PyObject *__pyx_tp_new_9maps_fast_BlockCyclicMap(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_9maps_fast_BlockCyclicMap *p;
  PyObject *o = __pyx_tp_new_9maps_fast_Map(t, a, k);
  if (!o) return 0;
  p = ((struct __pyx_obj_9maps_fast_BlockCyclicMap *)o);
  *(struct __pyx_vtabstruct_9maps_fast_BlockCyclicMap **)&p->__pyx_base.__pyx_vtab = __pyx_vtabptr_9maps_fast_BlockCyclicMap;
  return o;
}

static struct PyMethodDef __pyx_methods_9maps_fast_BlockCyclicMap[] = {
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_BlockCyclicMap = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_BlockCyclicMap = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_BlockCyclicMap = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_BlockCyclicMap = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_9maps_fast_BlockCyclicMap = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "maps_fast.BlockCyclicMap", /*tp_name*/
  sizeof(struct __pyx_obj_9maps_fast_BlockCyclicMap), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9maps_fast_Map, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_BlockCyclicMap, /*tp_as_number*/
  &__pyx_tp_as_sequence_BlockCyclicMap, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_BlockCyclicMap, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_BlockCyclicMap, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9maps_fast_BlockCyclicMap, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9maps_fast_BlockCyclicMap, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC init2maps_fast(void);

PyMODINIT_FUNC initmaps_fast(void); /*proto*/
PyMODINIT_FUNC initmaps_fast(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  /*--- Libary function declarations ---*/
  __pyx_init_filenames();
  /*--- Module creation code ---*/
  __pyx_m = Py_InitModule4("maps_fast", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- Intern code ---*/
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- String init code ---*/
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- Builtin init code ---*/
  __pyx_builtin_object = __Pyx_GetName(__pyx_b, __pyx_n_object); if (!__pyx_builtin_object) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_builtin_NotImplementedError = __Pyx_GetName(__pyx_b, __pyx_n_NotImplementedError); if (!__pyx_builtin_NotImplementedError) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_builtin_TypeError = __Pyx_GetName(__pyx_b, __pyx_n_TypeError); if (!__pyx_builtin_TypeError) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  if (__Pyx_ExportFunction("init2maps_fast", (void*)init2maps_fast, "int (void)") < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 0; __pyx_clineno = __LINE__; goto __pyx_L1;}
  /*--- Type init code ---*/
  __pyx_vtabptr_9maps_fast_Map = &__pyx_vtable_9maps_fast_Map;
  *(void(**)(void))&__pyx_vtable_9maps_fast_Map.owner_c = (void(*)(void))__pyx_f_9maps_fast_3Map_owner_c;
  *(void(**)(void))&__pyx_vtable_9maps_fast_Map.local_index_c = (void(*)(void))__pyx_f_9maps_fast_3Map_local_index_c;
  *(void(**)(void))&__pyx_vtable_9maps_fast_Map.global_index_c = (void(*)(void))__pyx_f_9maps_fast_3Map_global_index_c;
  if (PyType_Ready(&__pyx_type_9maps_fast_Map) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_9maps_fast_Map.tp_dict, __pyx_vtabptr_9maps_fast_Map) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Map", (PyObject *)&__pyx_type_9maps_fast_Map) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_9maps_fast_Map = &__pyx_type_9maps_fast_Map;
  __pyx_vtabptr_9maps_fast_BlockMap = &__pyx_vtable_9maps_fast_BlockMap;
  __pyx_vtable_9maps_fast_BlockMap.__pyx_base = *__pyx_vtabptr_9maps_fast_Map;
  *(void(**)(void))&__pyx_vtable_9maps_fast_BlockMap.__pyx_base.owner_c = (void(*)(void))__pyx_f_9maps_fast_8BlockMap_owner_c;
  *(void(**)(void))&__pyx_vtable_9maps_fast_BlockMap.__pyx_base.local_index_c = (void(*)(void))__pyx_f_9maps_fast_8BlockMap_local_index_c;
  *(void(**)(void))&__pyx_vtable_9maps_fast_BlockMap.__pyx_base.global_index_c = (void(*)(void))__pyx_f_9maps_fast_8BlockMap_global_index_c;
  __pyx_type_9maps_fast_BlockMap.tp_base = __pyx_ptype_9maps_fast_Map;
  if (PyType_Ready(&__pyx_type_9maps_fast_BlockMap) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_9maps_fast_BlockMap.tp_dict, __pyx_vtabptr_9maps_fast_BlockMap) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "BlockMap", (PyObject *)&__pyx_type_9maps_fast_BlockMap) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_9maps_fast_BlockMap = &__pyx_type_9maps_fast_BlockMap;
  __pyx_vtabptr_9maps_fast_CyclicMap = &__pyx_vtable_9maps_fast_CyclicMap;
  __pyx_vtable_9maps_fast_CyclicMap.__pyx_base = *__pyx_vtabptr_9maps_fast_Map;
  *(void(**)(void))&__pyx_vtable_9maps_fast_CyclicMap.__pyx_base.owner_c = (void(*)(void))__pyx_f_9maps_fast_9CyclicMap_owner_c;
  *(void(**)(void))&__pyx_vtable_9maps_fast_CyclicMap.__pyx_base.local_index_c = (void(*)(void))__pyx_f_9maps_fast_9CyclicMap_local_index_c;
  *(void(**)(void))&__pyx_vtable_9maps_fast_CyclicMap.__pyx_base.global_index_c = (void(*)(void))__pyx_f_9maps_fast_9CyclicMap_global_index_c;
  __pyx_type_9maps_fast_CyclicMap.tp_base = __pyx_ptype_9maps_fast_Map;
  if (PyType_Ready(&__pyx_type_9maps_fast_CyclicMap) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_9maps_fast_CyclicMap.tp_dict, __pyx_vtabptr_9maps_fast_CyclicMap) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "CyclicMap", (PyObject *)&__pyx_type_9maps_fast_CyclicMap) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_9maps_fast_CyclicMap = &__pyx_type_9maps_fast_CyclicMap;
  __pyx_vtabptr_9maps_fast_BlockCyclicMap = &__pyx_vtable_9maps_fast_BlockCyclicMap;
  __pyx_vtable_9maps_fast_BlockCyclicMap.__pyx_base = *__pyx_vtabptr_9maps_fast_Map;
  __pyx_type_9maps_fast_BlockCyclicMap.tp_base = __pyx_ptype_9maps_fast_Map;
  if (PyType_Ready(&__pyx_type_9maps_fast_BlockCyclicMap) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_9maps_fast_BlockCyclicMap.tp_dict, __pyx_vtabptr_9maps_fast_BlockCyclicMap) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "BlockCyclicMap", (PyObject *)&__pyx_type_9maps_fast_BlockCyclicMap) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_9maps_fast_BlockCyclicMap = &__pyx_type_9maps_fast_BlockCyclicMap;
  /*--- Type import code ---*/
  /*--- Function import code ---*/
  init2maps_fast();
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("maps_fast");
}

PyMODINIT_FUNC init2maps_fast(void); /*proto*/
PyMODINIT_FUNC init2maps_fast(void) {
  static int __Pyx_unique = 0;
  if (__Pyx_unique==1) return;
  __Pyx_unique = 1;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  /*--- Execution code ---*/

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":3
 * # include "../include/python.pxi"
 * 
 * import inspect             # <<<<<<<<<<<<<< 
 * 
 * from ipythondistarray.core.error import InvalidMapCode
 */
  __pyx_1 = __Pyx_Import(__pyx_n_inspect, 0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_inspect, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":5
 * import inspect
 * 
 * from ipythondistarray.core.error import InvalidMapCode             # <<<<<<<<<<<<<< 
 * 
 * cdef class Map:
 */
  __pyx_1 = PyList_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_InvalidMapCode);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_InvalidMapCode);
  __pyx_2 = __Pyx_Import(__pyx_k_2p, __pyx_1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_InvalidMapCode); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_InvalidMapCode, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":61
 *     pass
 * 
 * class MapRegistry(object):             # <<<<<<<<<<<<<< 
 *     
 *     def __init__(self):
 */
  __pyx_2 = PyDict_New(); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_builtin_object);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_builtin_object);
  __pyx_3 = __Pyx_CreateClass(__pyx_1, __pyx_2, __pyx_n_MapRegistry, "maps_fast"); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":63
 * class MapRegistry(object):
 *     
 *     def __init__(self):             # <<<<<<<<<<<<<< 
 *         self.maps = {}
 *         
 */
  __pyx_1 = PyCFunction_New(&__pyx_mdef_9maps_fast_11MapRegistry___init__, 0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_1, 0, __pyx_3); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n___init__, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":66
 *         self.maps = {}
 *         
 *     def register_map(self, code, m):             # <<<<<<<<<<<<<< 
 *         if inspect.isclass(m):
 *             if issubclass(m, Map):
 */
  __pyx_1 = PyCFunction_New(&__pyx_mdef_9maps_fast_11MapRegistry_register_map, 0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_1, 0, __pyx_3); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n_register_map, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":75
 *             raise TypeError("Must register a class")
 * 
 *     def get_map_class(self, code):             # <<<<<<<<<<<<<< 
 *         m = self.maps.get(code)
 *         if m is None:
 */
  __pyx_1 = PyCFunction_New(&__pyx_mdef_9maps_fast_11MapRegistry_get_map_class, 0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_1, 0, __pyx_3); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n_get_map_class, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_MapRegistry, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":89
 *             
 *             
 * _map_registry = MapRegistry()             # <<<<<<<<<<<<<< 
 * register_map = _map_registry.register_map
 * get_map_class = _map_registry.get_map_class
 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MapRegistry); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyObject_Call(__pyx_1, __pyx_empty_tuple, NULL); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n__map_registry, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":90
 *             
 * _map_registry = MapRegistry()
 * register_map = _map_registry.register_map             # <<<<<<<<<<<<<< 
 * get_map_class = _map_registry.get_map_class
 * 
 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n__map_registry); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_3, __pyx_n_register_map); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_register_map, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":91
 * _map_registry = MapRegistry()
 * register_map = _map_registry.register_map
 * get_map_class = _map_registry.get_map_class             # <<<<<<<<<<<<<< 
 * 
 * register_map('b', BlockMap)
 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n__map_registry); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyObject_GetAttr(__pyx_1, __pyx_n_get_map_class); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_get_map_class, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":93
 * get_map_class = _map_registry.get_map_class
 * 
 * register_map('b', BlockMap)             # <<<<<<<<<<<<<< 
 * register_map('c', CyclicMap)
 * register_map('bc', BlockCyclicMap)
 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_register_map); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_b);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_n_b);
  Py_INCREF(((PyObject*)__pyx_ptype_9maps_fast_BlockMap));
  PyTuple_SET_ITEM(__pyx_2, 1, ((PyObject*)__pyx_ptype_9maps_fast_BlockMap));
  __pyx_1 = PyObject_Call(__pyx_3, __pyx_2, NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":94
 * 
 * register_map('b', BlockMap)
 * register_map('c', CyclicMap)             # <<<<<<<<<<<<<< 
 * register_map('bc', BlockCyclicMap)
 * 
 */
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_register_map); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(2); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_c);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_n_c);
  Py_INCREF(((PyObject*)__pyx_ptype_9maps_fast_CyclicMap));
  PyTuple_SET_ITEM(__pyx_3, 1, ((PyObject*)__pyx_ptype_9maps_fast_CyclicMap));
  __pyx_2 = PyObject_Call(__pyx_4, __pyx_3, NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/ipythondistarray/core/maps_fast.pyx":95
 * register_map('b', BlockMap)
 * register_map('c', CyclicMap)
 * register_map('bc', BlockCyclicMap)             # <<<<<<<<<<<<<< 
 * 
 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_register_map); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(2); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_bc);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_n_bc);
  Py_INCREF(((PyObject*)__pyx_ptype_9maps_fast_BlockCyclicMap));
  PyTuple_SET_ITEM(__pyx_4, 1, ((PyObject*)__pyx_ptype_9maps_fast_BlockCyclicMap));
  __pyx_3 = PyObject_Call(__pyx_1, __pyx_4, NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("maps_fast");
}

static char *__pyx_filenames[] = {
  "maps_fast.pyx",
  "maps_fast",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static INLINE void __Pyx_RaiseArgtupleTooLong(
    Py_ssize_t num_expected,
    Py_ssize_t num_found)
{
    const char* error_message =
    #if PY_VERSION_HEX < 0x02050000
        "function takes at most %d positional arguments (%d given)";
    #else
        "function takes at most %zd positional arguments (%zd given)";
    #endif
    PyErr_Format(PyExc_TypeError, error_message, num_expected, num_found);
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                type = 0;
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static void __Pyx_WriteUnraisable(char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    PyErr_Fetch(&old_exc, &old_val, &old_tb);
    ctx = PyString_FromString(name);
    PyErr_Restore(old_exc, old_val, old_tb);
    if (!ctx)
        ctx = Py_None;
    PyErr_WriteUnraisable(ctx);
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        if (t->is_unicode) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_ExportFunction(char *name, void *f, char *sig) {
    PyObject *d = 0;
    PyObject *p = 0;
    d = PyObject_GetAttrString(__pyx_m, "__pyx_capi__");
    if (!d) {
        PyErr_Clear();
        d = PyDict_New();
        if (!d)
            goto bad;
        Py_INCREF(d);
        if (PyModule_AddObject(__pyx_m, "__pyx_capi__", d) < 0)
            goto bad;
    }
    p = PyCObject_FromVoidPtrAndDesc(f, sig, 0);
    if (!p)
        goto bad;
    if (PyDict_SetItemString(d, name, p) < 0)
        goto bad;
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(p);
    Py_XDECREF(d);
    return -1;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        py_funcname = PyString_FromFormat( "%s (%s:%u)", funcname, __pyx_cfilenm, __pyx_clineno);
    }
    else {
        py_funcname = PyString_FromString(funcname);
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}
