/* Generated by Cython 0.9.6.10b on Sat Jan 26 11:05:46 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#ifndef WIN32
  #define __stdcall
  #define __cdecl
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "stdlib.h"


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n; int is_unicode;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from procgrid_fast */

/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pxd":2
 * 
 * cdef class ProcGrid:             # <<<<<<<<<<<<<< 
 * 
 *     cdef readonly int ndim
 */

struct __pyx_obj_13procgrid_fast_ProcGrid {
  PyObject_HEAD
  struct __pyx_vtabstruct_13procgrid_fast_ProcGrid *__pyx_vtab;
  int ndim;
  int *strides;
  PyObject *shape;
};


/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":5
 * include "../include/stdlib.pxi"
 * 
 * cdef class ProcGrid:             # <<<<<<<<<<<<<< 
 * 
 *     def __cinit__(self, object shape):
 */

struct __pyx_vtabstruct_13procgrid_fast_ProcGrid {
  int (*c_global_rank)(struct __pyx_obj_13procgrid_fast_ProcGrid *,int *);
};
static struct __pyx_vtabstruct_13procgrid_fast_ProcGrid *__pyx_vtabptr_13procgrid_fast_ProcGrid;

static PyTypeObject *__pyx_ptype_13procgrid_fast_ProcGrid = 0;


/* Implementation of procgrid_fast */

static PyObject *__pyx_n___cinit__;
static PyObject *__pyx_n___dealloc__;
static PyObject *__pyx_n___getitem__;

/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":7
 * cdef class ProcGrid:
 * 
 *     def __cinit__(self, object shape):             # <<<<<<<<<<<<<< 
 *         cdef Py_ssize_t i
 *     
 */

static PyObject *__pyx_n_TypeError;

static PyObject *__pyx_k1p;

static PyObject *__pyx_builtin_TypeError;

static char __pyx_k1[] = "The shape argument must be a sequence";

static int __pyx_pf_13procgrid_fast_8ProcGrid___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_pf_13procgrid_fast_8ProcGrid___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_shape = 0;
  Py_ssize_t __pyx_v_i;
  int __pyx_r;
  int __pyx_1;
  int __pyx_2;
  Py_ssize_t __pyx_3;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  int __pyx_6;
  static char *__pyx_argnames[] = {"shape",0};
  if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_shape))) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_shape);

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":10
 *         cdef Py_ssize_t i
 *     
 *         if PySequence_Check(shape):             # <<<<<<<<<<<<<< 
 *             self.ndim = PySequence_Length(shape)
 *             self.strides = <int *>PyMem_Malloc(self.ndim*sizeof(int))
 */
  __pyx_1 = PySequence_Check(__pyx_v_shape);
  if (__pyx_1) {

    /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":11
 *     
 *         if PySequence_Check(shape):
 *             self.ndim = PySequence_Length(shape)             # <<<<<<<<<<<<<< 
 *             self.strides = <int *>PyMem_Malloc(self.ndim*sizeof(int))
 *             for i from 0 <= i < self.ndim:
 */
    ((struct __pyx_obj_13procgrid_fast_ProcGrid *)__pyx_v_self)->ndim = PySequence_Length(__pyx_v_shape);

    /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":12
 *         if PySequence_Check(shape):
 *             self.ndim = PySequence_Length(shape)
 *             self.strides = <int *>PyMem_Malloc(self.ndim*sizeof(int))             # <<<<<<<<<<<<<< 
 *             for i from 0 <= i < self.ndim:
 *                 self.strides[i] = shape[self.ndim-i-1]
 */
    ((struct __pyx_obj_13procgrid_fast_ProcGrid *)__pyx_v_self)->strides = ((int *)PyMem_Malloc((((struct __pyx_obj_13procgrid_fast_ProcGrid *)__pyx_v_self)->ndim * (sizeof(int)))));

    /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":13
 *             self.ndim = PySequence_Length(shape)
 *             self.strides = <int *>PyMem_Malloc(self.ndim*sizeof(int))
 *             for i from 0 <= i < self.ndim:             # <<<<<<<<<<<<<< 
 *                 self.strides[i] = shape[self.ndim-i-1]
 *             self.strides[self.ndim-1] = 1
 */
    __pyx_2 = ((struct __pyx_obj_13procgrid_fast_ProcGrid *)__pyx_v_self)->ndim;
    for (__pyx_v_i = 0; __pyx_v_i < __pyx_2; __pyx_v_i++) {

      /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":14
 *             self.strides = <int *>PyMem_Malloc(self.ndim*sizeof(int))
 *             for i from 0 <= i < self.ndim:
 *                 self.strides[i] = shape[self.ndim-i-1]             # <<<<<<<<<<<<<< 
 *             self.strides[self.ndim-1] = 1
 *             self.shape = tuple(shape)
 */
      __pyx_3 = ((((struct __pyx_obj_13procgrid_fast_ProcGrid *)__pyx_v_self)->ndim - __pyx_v_i) - 1);
      if (PyList_CheckExact(__pyx_v_shape) && 0 <= __pyx_3 && __pyx_3 < PyList_GET_SIZE(__pyx_v_shape)) {
        __pyx_5 = PyList_GET_ITEM(__pyx_v_shape, __pyx_3); Py_INCREF(__pyx_5);
        } else if (PyTuple_CheckExact(__pyx_v_shape) && 0 <= __pyx_3 && __pyx_3 < PyTuple_GET_SIZE(__pyx_v_shape)) {
        __pyx_5 = PyTuple_GET_ITEM(__pyx_v_shape, __pyx_3); Py_INCREF(__pyx_5);
        } else {
        __pyx_4 = PyInt_FromSsize_t(__pyx_3); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; goto __pyx_L1;}
        __pyx_5 = PyObject_GetItem(__pyx_v_shape, __pyx_4); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; goto __pyx_L1;}
        Py_DECREF(__pyx_4); __pyx_4 = 0;
      }
      __pyx_6 = __pyx_PyInt_int(__pyx_5); if (unlikely((__pyx_6 == -1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      (((struct __pyx_obj_13procgrid_fast_ProcGrid *)__pyx_v_self)->strides[__pyx_v_i]) = __pyx_6;
    }

    /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":15
 *             for i from 0 <= i < self.ndim:
 *                 self.strides[i] = shape[self.ndim-i-1]
 *             self.strides[self.ndim-1] = 1             # <<<<<<<<<<<<<< 
 *             self.shape = tuple(shape)
 *         else:
 */
    (((struct __pyx_obj_13procgrid_fast_ProcGrid *)__pyx_v_self)->strides[(((struct __pyx_obj_13procgrid_fast_ProcGrid *)__pyx_v_self)->ndim - 1)]) = 1;

    /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":16
 *                 self.strides[i] = shape[self.ndim-i-1]
 *             self.strides[self.ndim-1] = 1
 *             self.shape = tuple(shape)             # <<<<<<<<<<<<<< 
 *         else:
 *             raise TypeError("The shape argument must be a sequence")
 */
    __pyx_4 = PyTuple_New(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
    Py_INCREF(__pyx_v_shape);
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_shape);
    __pyx_5 = PyObject_CallObject(((PyObject*)&PyTuple_Type), __pyx_4); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(((struct __pyx_obj_13procgrid_fast_ProcGrid *)__pyx_v_self)->shape);
    ((struct __pyx_obj_13procgrid_fast_ProcGrid *)__pyx_v_self)->shape = __pyx_5;
    __pyx_5 = 0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":18
 *             self.shape = tuple(shape)
 *         else:
 *             raise TypeError("The shape argument must be a sequence")             # <<<<<<<<<<<<<< 
 * 
 *     def __dealloc__(self):
 */
    __pyx_4 = PyTuple_New(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
    Py_INCREF(__pyx_k1p);
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_k1p);
    __pyx_5 = PyObject_CallObject(__pyx_builtin_TypeError, __pyx_4); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  }
  __pyx_L2:;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("procgrid_fast.ProcGrid.__cinit__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_shape);
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":20
 *             raise TypeError("The shape argument must be a sequence")
 * 
 *     def __dealloc__(self):             # <<<<<<<<<<<<<< 
 *         PyMem_Free(self.strides)
 *     
 */

static void __pyx_pf_13procgrid_fast_8ProcGrid___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_pf_13procgrid_fast_8ProcGrid___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":21
 * 
 *     def __dealloc__(self):
 *         PyMem_Free(self.strides)             # <<<<<<<<<<<<<< 
 *     
 *     cdef int c_global_rank(self, int *proc_indices):
 */
  PyMem_Free(((struct __pyx_obj_13procgrid_fast_ProcGrid *)__pyx_v_self)->strides);

  Py_DECREF(__pyx_v_self);
}

/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":23
 *         PyMem_Free(self.strides)
 *     
 *     cdef int c_global_rank(self, int *proc_indices):             # <<<<<<<<<<<<<< 
 *         cdef Py_ssize_t i
 *         cdef int rank = 0
 */

static  int __pyx_f_13procgrid_fast_8ProcGrid_c_global_rank(struct __pyx_obj_13procgrid_fast_ProcGrid *__pyx_v_self,int *__pyx_v_proc_indices) {
  Py_ssize_t __pyx_v_i;
  int __pyx_v_rank;
  int __pyx_r;
  int __pyx_1;
  Py_INCREF(__pyx_v_self);

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":25
 *     cdef int c_global_rank(self, int *proc_indices):
 *         cdef Py_ssize_t i
 *         cdef int rank = 0             # <<<<<<<<<<<<<< 
 *         
 *         for i from 0 <= i < self.ndim:
 */
  __pyx_v_rank = 0;


  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":27
 *         cdef int rank = 0
 *         
 *         for i from 0 <= i < self.ndim:             # <<<<<<<<<<<<<< 
 *             rank += self.strides[i]*proc_indices[i]
 *         return rank
 */
  __pyx_1 = __pyx_v_self->ndim;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; __pyx_v_i++) {

    /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":28
 *         
 *         for i from 0 <= i < self.ndim:
 *             rank += self.strides[i]*proc_indices[i]             # <<<<<<<<<<<<<< 
 *         return rank
 *     
 */
    __pyx_v_rank += ((__pyx_v_self->strides[__pyx_v_i]) * (__pyx_v_proc_indices[__pyx_v_i]));
  }

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":29
 *         for i from 0 <= i < self.ndim:
 *             rank += self.strides[i]*proc_indices[i]
 *         return rank             # <<<<<<<<<<<<<< 
 *     
 *     def __getitem__(self, object indices):
 */
  __pyx_r = __pyx_v_rank;
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

/* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":31
 *         return rank
 *     
 *     def __getitem__(self, object indices):             # <<<<<<<<<<<<<< 
 *   
 *         cdef Py_ssize_t i
 */

static PyObject *__pyx_n_IndexError;

static PyObject *__pyx_k2p;
static PyObject *__pyx_k3p;

static PyObject *__pyx_builtin_IndexError;

static char __pyx_k2[] = "Number of indices must match ndim (%s)";
static char __pyx_k3[] = "This class only supports simple indexing";

static PyObject *__pyx_pf_13procgrid_fast_8ProcGrid___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_indices); /*proto*/
static PyObject *__pyx_pf_13procgrid_fast_8ProcGrid___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_indices) {
  Py_ssize_t __pyx_v_i;
  int *__pyx_v_proc_indices;
  PyObject *__pyx_v_rank;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  int __pyx_5;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_indices);
  __pyx_v_rank = Py_None; Py_INCREF(Py_None);

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":37
 *         cdef rank
 *         
 *         if PyTuple_Check(indices):             # <<<<<<<<<<<<<< 
 *             if PyTuple_Size(indices) != self.ndim:
 *                 raise IndexError("Number of indices must match ndim (%s)" % self.ndim)
 */
  __pyx_1 = PyTuple_Check(__pyx_v_indices);
  if (__pyx_1) {

    /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":38
 *         
 *         if PyTuple_Check(indices):
 *             if PyTuple_Size(indices) != self.ndim:             # <<<<<<<<<<<<<< 
 *                 raise IndexError("Number of indices must match ndim (%s)" % self.ndim)
 * 
 */
    __pyx_1 = (PyTuple_Size(__pyx_v_indices) != ((struct __pyx_obj_13procgrid_fast_ProcGrid *)__pyx_v_self)->ndim);
    if (__pyx_1) {

      /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":39
 *         if PyTuple_Check(indices):
 *             if PyTuple_Size(indices) != self.ndim:
 *                 raise IndexError("Number of indices must match ndim (%s)" % self.ndim)             # <<<<<<<<<<<<<< 
 * 
 *             proc_indices = <int *>malloc(self.ndim*sizeof(int))
 */
      __pyx_2 = PyInt_FromLong(((struct __pyx_obj_13procgrid_fast_ProcGrid *)__pyx_v_self)->ndim); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
      __pyx_3 = PyNumber_Remainder(__pyx_k2p, __pyx_2); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
      __pyx_3 = 0;
      __pyx_3 = PyObject_CallObject(__pyx_builtin_IndexError, __pyx_2); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __Pyx_Raise(__pyx_3, 0, 0);
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
      goto __pyx_L3;
    }
    __pyx_L3:;

    /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":41
 *                 raise IndexError("Number of indices must match ndim (%s)" % self.ndim)
 * 
 *             proc_indices = <int *>malloc(self.ndim*sizeof(int))             # <<<<<<<<<<<<<< 
 *             for i from 0 <= i < self.ndim:
 *                 proc_indices[i] = <object>PyTuple_GET_ITEM(indices, i)
 */
    __pyx_v_proc_indices = ((int *)malloc((((struct __pyx_obj_13procgrid_fast_ProcGrid *)__pyx_v_self)->ndim * (sizeof(int)))));

    /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":42
 * 
 *             proc_indices = <int *>malloc(self.ndim*sizeof(int))
 *             for i from 0 <= i < self.ndim:             # <<<<<<<<<<<<<< 
 *                 proc_indices[i] = <object>PyTuple_GET_ITEM(indices, i)
 *             rank = self.c_global_rank(proc_indices)
 */
    __pyx_4 = ((struct __pyx_obj_13procgrid_fast_ProcGrid *)__pyx_v_self)->ndim;
    for (__pyx_v_i = 0; __pyx_v_i < __pyx_4; __pyx_v_i++) {

      /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":43
 *             proc_indices = <int *>malloc(self.ndim*sizeof(int))
 *             for i from 0 <= i < self.ndim:
 *                 proc_indices[i] = <object>PyTuple_GET_ITEM(indices, i)             # <<<<<<<<<<<<<< 
 *             rank = self.c_global_rank(proc_indices)
 *             free(proc_indices)
 */
      __pyx_2 = (PyObject *)PyTuple_GET_ITEM(__pyx_v_indices,__pyx_v_i);
      Py_INCREF(__pyx_2);
      __pyx_5 = __pyx_PyInt_int(__pyx_2); if (unlikely((__pyx_5 == -1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      (__pyx_v_proc_indices[__pyx_v_i]) = __pyx_5;
    }

    /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":44
 *             for i from 0 <= i < self.ndim:
 *                 proc_indices[i] = <object>PyTuple_GET_ITEM(indices, i)
 *             rank = self.c_global_rank(proc_indices)             # <<<<<<<<<<<<<< 
 *             free(proc_indices)
 *             return rank
 */
    __pyx_3 = PyInt_FromLong(((struct __pyx_vtabstruct_13procgrid_fast_ProcGrid *)((struct __pyx_obj_13procgrid_fast_ProcGrid *)__pyx_v_self)->__pyx_vtab)->c_global_rank(((struct __pyx_obj_13procgrid_fast_ProcGrid *)__pyx_v_self),__pyx_v_proc_indices)); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
    Py_DECREF(__pyx_v_rank);
    __pyx_v_rank = __pyx_3;
    __pyx_3 = 0;

    /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":45
 *                 proc_indices[i] = <object>PyTuple_GET_ITEM(indices, i)
 *             rank = self.c_global_rank(proc_indices)
 *             free(proc_indices)             # <<<<<<<<<<<<<< 
 *             return rank
 *         else:
 */
    free(__pyx_v_proc_indices);

    /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":46
 *             rank = self.c_global_rank(proc_indices)
 *             free(proc_indices)
 *             return rank             # <<<<<<<<<<<<<< 
 *         else:
 *             raise IndexError("This class only supports simple indexing")
 */
    Py_INCREF(__pyx_v_rank);
    __pyx_r = __pyx_v_rank;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":48
 *             return rank
 *         else:
 *             raise IndexError("This class only supports simple indexing")             # <<<<<<<<<<<<<< 
 * 
 * 
 */
    __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
    Py_INCREF(__pyx_k3p);
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_k3p);
    __pyx_3 = PyObject_CallObject(__pyx_builtin_IndexError, __pyx_2); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __Pyx_Raise(__pyx_3, 0, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("procgrid_fast.ProcGrid.__getitem__");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_rank);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_indices);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_IndexError, "IndexError"},
  {&__pyx_n_TypeError, "TypeError"},
  {&__pyx_n___cinit__, "__cinit__"},
  {&__pyx_n___dealloc__, "__dealloc__"},
  {&__pyx_n___getitem__, "__getitem__"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k1p, __pyx_k1, sizeof(__pyx_k1), 0},
  {&__pyx_k2p, __pyx_k2, sizeof(__pyx_k2), 0},
  {&__pyx_k3p, __pyx_k3, sizeof(__pyx_k3), 0},
  {0, 0, 0, 0}
};
static struct __pyx_vtabstruct_13procgrid_fast_ProcGrid __pyx_vtable_13procgrid_fast_ProcGrid;

static PyObject *__pyx_tp_new_13procgrid_fast_ProcGrid(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_13procgrid_fast_ProcGrid *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_13procgrid_fast_ProcGrid *)o);
  *(struct __pyx_vtabstruct_13procgrid_fast_ProcGrid **)&p->__pyx_vtab = __pyx_vtabptr_13procgrid_fast_ProcGrid;
  p->shape = Py_None; Py_INCREF(Py_None);
  if (__pyx_pf_13procgrid_fast_8ProcGrid___cinit__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_13procgrid_fast_ProcGrid(PyObject *o) {
  struct __pyx_obj_13procgrid_fast_ProcGrid *p = (struct __pyx_obj_13procgrid_fast_ProcGrid *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_pf_13procgrid_fast_8ProcGrid___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  Py_XDECREF(p->shape);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_13procgrid_fast_ProcGrid(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_13procgrid_fast_ProcGrid *p = (struct __pyx_obj_13procgrid_fast_ProcGrid *)o;
  if (p->shape) {
    e = (*v)(p->shape, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_13procgrid_fast_ProcGrid(PyObject *o) {
  struct __pyx_obj_13procgrid_fast_ProcGrid *p = (struct __pyx_obj_13procgrid_fast_ProcGrid *)o;
  Py_XDECREF(p->shape);
  p->shape = Py_None; Py_INCREF(Py_None);
  return 0;
}
static PyObject *__pyx_sq_item_13procgrid_fast_ProcGrid(PyObject *o, Py_ssize_t i) {
  PyObject *r;
  PyObject *x = PyInt_FromSsize_t(i); if(!x) return 0;
  r = o->ob_type->tp_as_mapping->mp_subscript(o, x);
  Py_DECREF(x);
  return r;
}

static struct PyMethodDef __pyx_methods_13procgrid_fast_ProcGrid[] = {
  {"__getitem__", (PyCFunction)__pyx_pf_13procgrid_fast_8ProcGrid___getitem__, METH_O|METH_COEXIST, 0},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_13procgrid_fast_ProcGrid[] = {
  {"ndim", T_INT, offsetof(struct __pyx_obj_13procgrid_fast_ProcGrid, ndim), READONLY, 0},
  {"shape", T_OBJECT, offsetof(struct __pyx_obj_13procgrid_fast_ProcGrid, shape), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_ProcGrid = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_ProcGrid = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  __pyx_sq_item_13procgrid_fast_ProcGrid, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_ProcGrid = {
  0, /*mp_length*/
  __pyx_pf_13procgrid_fast_8ProcGrid___getitem__, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_ProcGrid = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_13procgrid_fast_ProcGrid = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "procgrid_fast.ProcGrid", /*tp_name*/
  sizeof(struct __pyx_obj_13procgrid_fast_ProcGrid), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_13procgrid_fast_ProcGrid, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_ProcGrid, /*tp_as_number*/
  &__pyx_tp_as_sequence_ProcGrid, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_ProcGrid, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_ProcGrid, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_13procgrid_fast_ProcGrid, /*tp_traverse*/
  __pyx_tp_clear_13procgrid_fast_ProcGrid, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_13procgrid_fast_ProcGrid, /*tp_methods*/
  __pyx_members_13procgrid_fast_ProcGrid, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_13procgrid_fast_ProcGrid, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initprocgrid_fast(void); /*proto*/
PyMODINIT_FUNC initprocgrid_fast(void) {
  /*--- Libary function declarations ---*/
  __pyx_init_filenames();
  /*--- Module creation code ---*/
  __pyx_m = Py_InitModule4("procgrid_fast", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  /*--- Intern code ---*/
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  /*--- String init code ---*/
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  /*--- Builtin init code ---*/
  __pyx_builtin_TypeError = __Pyx_GetName(__pyx_b, __pyx_n_TypeError); if (!__pyx_builtin_TypeError) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  __pyx_builtin_IndexError = __Pyx_GetName(__pyx_b, __pyx_n_IndexError); if (!__pyx_builtin_IndexError) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Function import code ---*/
  /*--- Type init code ---*/
  __pyx_vtabptr_13procgrid_fast_ProcGrid = &__pyx_vtable_13procgrid_fast_ProcGrid;
  *(void(**)(void))&__pyx_vtable_13procgrid_fast_ProcGrid.c_global_rank = (void(*)(void))__pyx_f_13procgrid_fast_8ProcGrid_c_global_rank;
  __pyx_type_13procgrid_fast_ProcGrid.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_13procgrid_fast_ProcGrid) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_13procgrid_fast_ProcGrid.tp_dict, __pyx_vtabptr_13procgrid_fast_ProcGrid) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "ProcGrid", (PyObject *)&__pyx_type_13procgrid_fast_ProcGrid) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; goto __pyx_L1;}
  __pyx_ptype_13procgrid_fast_ProcGrid = &__pyx_type_13procgrid_fast_ProcGrid;
  /*--- Type import code ---*/
  /*--- Execution code ---*/

  /* "/Users/bgranger/Documents/Computation/IPython/Working/ipythondistarray/trunk/ipythondistarray/core/procgrid_fast.pyx":31
 *         return rank
 *     
 *     def __getitem__(self, object indices):             # <<<<<<<<<<<<<< 
 *   
 *         cdef Py_ssize_t i
 */
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("procgrid_fast");
}

static char *__pyx_filenames[] = {
  "procgrid_fast.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        if (t->is_unicode) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        PY_LONG_LONG val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        PY_LONG_LONG val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}
