/* Generated by Cython 0.9.8 on Mon Jul  7 10:39:01 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifndef DL_EXPORT
  #define DL_EXPORT(t) t
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02060000
  #define Py_REFCNT(ob) (((PyObject*)(ob))->ob_refcnt)
  #define Py_TYPE(ob)   (((PyObject*)(ob))->ob_type)
  #define Py_SIZE(ob)   ((PyVarObject*)(ob))->ob_size)
  #define PyVarObject_HEAD_INIT(type, size) \
          PyObject_HEAD_INIT(type) size,

  typedef struct {
       void *buf;
       Py_ssize_t len;
       int readonly;
       const char *format;
       int ndim;
       Py_ssize_t *shape;
       Py_ssize_t *strides;
       Py_ssize_t *suboffsets;
       Py_ssize_t itemsize;
       void *internal;
  } Py_buffer;

  #define PyBUF_SIMPLE 0
  #define PyBUF_WRITABLE 0x0001
  #define PyBUF_LOCK 0x0002
  #define PyBUF_FORMAT 0x0004
  #define PyBUF_ND 0x0008
  #define PyBUF_STRIDES (0x0010 | PyBUF_ND)
  #define PyBUF_C_CONTIGUOUS (0x0020 | PyBUF_STRIDES)
  #define PyBUF_F_CONTIGUOUS (0x0040 | PyBUF_STRIDES)
  #define PyBUF_ANY_CONTIGUOUS (0x0080 | PyBUF_STRIDES)
  #define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)
#endif
#if PY_MAJOR_VERSION < 3
  #define __Pyx_BUILTIN_MODULE_NAME "__builtin__"
#else
  #define __Pyx_BUILTIN_MODULE_NAME "builtins"
#endif
#if PY_MAJOR_VERSION >= 3
  #define Py_TPFLAGS_CHECKTYPES 0
  #define Py_TPFLAGS_HAVE_INDEX 0
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyBaseString_Type            PyUnicode_Type
  #define PyString_Type                PyBytes_Type
  #define PyInt_Type                   PyLong_Type
  #define PyInt_Check(op)              PyLong_Check(op)
  #define PyInt_CheckExact(op)         PyLong_CheckExact(op)
  #define PyInt_FromString             PyLong_FromString
  #define PyInt_FromUnicode            PyLong_FromUnicode
  #define PyInt_FromLong               PyLong_FromLong
  #define PyInt_FromSize_t             PyLong_FromSize_t
  #define PyInt_FromSsize_t            PyLong_FromSsize_t
  #define PyInt_AsLong                 PyLong_AsLong
  #define PyInt_AS_LONG                PyLong_AS_LONG
  #define PyInt_AsSsize_t              PyLong_AsSsize_t
  #define PyInt_AsUnsignedLongMask     PyLong_AsUnsignedLongMask
  #define PyInt_AsUnsignedLongLongMask PyLong_AsUnsignedLongLongMask
  #define PyNumber_Divide(x,y)         PyNumber_TrueDivide(x,y)
#else
  #define PyBytes_Type                 PyString_Type
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyMethod_New(func, self, klass) PyInstanceMethod_New(func)
#endif
#ifndef __stdcall
  #define __stdcall
#endif
#ifndef __cdecl
  #define __cdecl
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#define __PYX_HAVE_API__distarray__mpi__tests__helloworld
#include "mpi.h"
#include "mpi4py/mpi4py.h"


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s; long n; char is_unicode; char intern; char is_identifier;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#if PY_MAJOR_VERSION < 3
#define __Pyx_PyBytes_FromString PyString_FromString
#define __Pyx_PyBytes_AsString   PyString_AsString
#else
#define __Pyx_PyBytes_FromString PyBytes_FromString
#define __Pyx_PyBytes_AsString   PyBytes_AsString
#endif

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static const char * __pyx_cfilenm= __FILE__;
static const char *__pyx_filename;
static const char **__pyx_f;

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static int __Pyx_Print(PyObject *, int); /*proto*/
#if PY_MAJOR_VERSION >= 3
static PyObject* __pyx_print = 0;
static PyObject* __pyx_print_kwargs = 0;
#endif

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/

static PyObject *__Pyx_ImportModule(char *name); /*proto*/

static void __Pyx_AddTraceback(const char *funcname); /*proto*/

/* Type declarations */
/* Module declarations from mpi4py.MPI */

/* Module declarations from mpi4py.MPI */

static PyTypeObject *__pyx_ptype_6mpi4py_3MPI_Status = 0;
static PyTypeObject *__pyx_ptype_6mpi4py_3MPI_Datatype = 0;
static PyTypeObject *__pyx_ptype_6mpi4py_3MPI_Request = 0;
static PyTypeObject *__pyx_ptype_6mpi4py_3MPI_Prequest = 0;
static PyTypeObject *__pyx_ptype_6mpi4py_3MPI_Grequest = 0;
static PyTypeObject *__pyx_ptype_6mpi4py_3MPI_Op = 0;
static PyTypeObject *__pyx_ptype_6mpi4py_3MPI_Group = 0;
static PyTypeObject *__pyx_ptype_6mpi4py_3MPI_Info = 0;
static PyTypeObject *__pyx_ptype_6mpi4py_3MPI_Errhandler = 0;
static PyTypeObject *__pyx_ptype_6mpi4py_3MPI_Comm = 0;
static PyTypeObject *__pyx_ptype_6mpi4py_3MPI_Intracomm = 0;
static PyTypeObject *__pyx_ptype_6mpi4py_3MPI_Cartcomm = 0;
static PyTypeObject *__pyx_ptype_6mpi4py_3MPI_Graphcomm = 0;
static PyTypeObject *__pyx_ptype_6mpi4py_3MPI_Intercomm = 0;
static PyTypeObject *__pyx_ptype_6mpi4py_3MPI_Win = 0;
static PyTypeObject *__pyx_ptype_6mpi4py_3MPI_File = 0;
/* Module declarations from mpi4py.mpi_c */

/* Module declarations from distarray.mpi.tests.helloworld */

static PyMPICommObject *__pyx_v_9distarray_3mpi_5tests_10helloworld_WORLD = 0;
static PyMPIIntracommObject *__pyx_v_9distarray_3mpi_5tests_10helloworld_SELF = 0;
static MPI_Comm __pyx_v_9distarray_3mpi_5tests_10helloworld_world1;
static MPI_Comm __pyx_v_9distarray_3mpi_5tests_10helloworld_world2;
static int __pyx_v_9distarray_3mpi_5tests_10helloworld_ierr1;
static int __pyx_v_9distarray_3mpi_5tests_10helloworld_size1;
static int __pyx_v_9distarray_3mpi_5tests_10helloworld_rank1;
static int __pyx_v_9distarray_3mpi_5tests_10helloworld_rlen1;
static char __pyx_v_9distarray_3mpi_5tests_10helloworld_pname1[MPI_MAX_PROCESSOR_NAME];
static MPI_Comm __pyx_v_9distarray_3mpi_5tests_10helloworld_world3;
static MPI_Comm __pyx_v_9distarray_3mpi_5tests_10helloworld_world4;
static int __pyx_v_9distarray_3mpi_5tests_10helloworld_ierr2;
static int __pyx_v_9distarray_3mpi_5tests_10helloworld_size2;
static int __pyx_v_9distarray_3mpi_5tests_10helloworld_rank2;
static int __pyx_v_9distarray_3mpi_5tests_10helloworld_rlen2;
static char __pyx_v_9distarray_3mpi_5tests_10helloworld_pname2[MPI_MAX_PROCESSOR_NAME];


/* Implementation of distarray.mpi.tests.helloworld */

static char __pyx_k_2[] = "Hello, World! I am process %d of %d on %s.";
static char __pyx_k_3[] = "Hello, World! I am process %d of %d on %s.";
static char __pyx_k_4[] = "Hello, World! I am process %d of %d on %s.";

static char __pyx_k_1[] = "mpi4py";
static char __pyx_k_MPI[] = "MPI";
static char __pyx_k_COMM_WORLD[] = "COMM_WORLD";
static char __pyx_k_Get_size[] = "Get_size";
static char __pyx_k_size[] = "size";
static char __pyx_k_Get_rank[] = "Get_rank";
static char __pyx_k_rank[] = "rank";
static char __pyx_k_Get_processor_name[] = "Get_processor_name";
static char __pyx_k_pname[] = "pname";
static char __pyx_k_hwmess[] = "hwmess";
static char __pyx_k_COMM_SELF[] = "COMM_SELF";

static PyObject *__pyx_kp_1;
static PyObject *__pyx_kp_MPI;
static PyObject *__pyx_kp_COMM_WORLD;
static PyObject *__pyx_kp_Get_size;
static PyObject *__pyx_kp_size;
static PyObject *__pyx_kp_Get_rank;
static PyObject *__pyx_kp_rank;
static PyObject *__pyx_kp_Get_processor_name;
static PyObject *__pyx_kp_pname;
static PyObject *__pyx_kp_hwmess;
static PyObject *__pyx_kp_COMM_SELF;

static PyObject *__pyx_kp_2;
static PyObject *__pyx_kp_3;
static PyObject *__pyx_kp_4;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_kp_1, __pyx_k_1, sizeof(__pyx_k_1), 1, 1, 1},
  {&__pyx_kp_MPI, __pyx_k_MPI, sizeof(__pyx_k_MPI), 1, 1, 1},
  {&__pyx_kp_COMM_WORLD, __pyx_k_COMM_WORLD, sizeof(__pyx_k_COMM_WORLD), 1, 1, 1},
  {&__pyx_kp_Get_size, __pyx_k_Get_size, sizeof(__pyx_k_Get_size), 1, 1, 1},
  {&__pyx_kp_size, __pyx_k_size, sizeof(__pyx_k_size), 1, 1, 1},
  {&__pyx_kp_Get_rank, __pyx_k_Get_rank, sizeof(__pyx_k_Get_rank), 1, 1, 1},
  {&__pyx_kp_rank, __pyx_k_rank, sizeof(__pyx_k_rank), 1, 1, 1},
  {&__pyx_kp_Get_processor_name, __pyx_k_Get_processor_name, sizeof(__pyx_k_Get_processor_name), 1, 1, 1},
  {&__pyx_kp_pname, __pyx_k_pname, sizeof(__pyx_k_pname), 1, 1, 1},
  {&__pyx_kp_hwmess, __pyx_k_hwmess, sizeof(__pyx_k_hwmess), 1, 1, 1},
  {&__pyx_kp_2, __pyx_k_2, sizeof(__pyx_k_2), 0, 0, 0},
  {&__pyx_kp_COMM_SELF, __pyx_k_COMM_SELF, sizeof(__pyx_k_COMM_SELF), 1, 1, 1},
  {&__pyx_kp_3, __pyx_k_3, sizeof(__pyx_k_3), 0, 0, 0},
  {&__pyx_kp_4, __pyx_k_4, sizeof(__pyx_k_4), 0, 0, 0},
  {0, 0, 0, 0, 0}
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

#if PY_MAJOR_VERSION >= 3
static struct PyModuleDef __pyx_moduledef = {
    PyModuleDef_HEAD_INIT,
    "helloworld",
    0, /* m_doc */
    -1, /* m_size */
    __pyx_methods /* m_methods */,
    NULL, /* m_reload */
    NULL, /* m_traverse */
    NULL, /* m_clear */
    NULL /* m_free */
};
#endif

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC inithelloworld(void); /*proto*/
PyMODINIT_FUNC inithelloworld(void)
#else
PyMODINIT_FUNC PyInit_helloworld(void); /*proto*/
PyMODINIT_FUNC PyInit_helloworld(void)
#endif
{
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; __pyx_clineno = __LINE__; goto __pyx_L1;}
  /*--- Libary function declarations ---*/
  __pyx_init_filenames();
  /*--- Module creation code ---*/
  #if PY_MAJOR_VERSION < 3
  __pyx_m = Py_InitModule4("helloworld", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  #else
  __pyx_m = PyModule_Create(&__pyx_moduledef);
  #endif
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; __pyx_clineno = __LINE__; goto __pyx_L1;};
  #if PY_MAJOR_VERSION < 3
  Py_INCREF(__pyx_m);
  #endif
  __pyx_b = PyImport_AddModule(__Pyx_BUILTIN_MODULE_NAME);
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; __pyx_clineno = __LINE__; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- Intern code ---*/
  /*--- String init code ---*/
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- Builtin init code ---*/
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  __pyx_v_9distarray_3mpi_5tests_10helloworld_WORLD = ((PyMPICommObject *)Py_None); Py_INCREF(Py_None);
  __pyx_v_9distarray_3mpi_5tests_10helloworld_SELF = ((PyMPIIntracommObject *)Py_None); Py_INCREF(Py_None);
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  /*--- Type import code ---*/
  __pyx_ptype_6mpi4py_3MPI_Status = __Pyx_ImportType("mpi4py.MPI", "Status", sizeof(PyMPIStatusObject)); if (unlikely(!__pyx_ptype_6mpi4py_3MPI_Status)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 46; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_6mpi4py_3MPI_Datatype = __Pyx_ImportType("mpi4py.MPI", "Datatype", sizeof(PyMPIDatatypeObject)); if (unlikely(!__pyx_ptype_6mpi4py_3MPI_Datatype)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 49; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_6mpi4py_3MPI_Request = __Pyx_ImportType("mpi4py.MPI", "Request", sizeof(PyMPIRequestObject)); if (unlikely(!__pyx_ptype_6mpi4py_3MPI_Request)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 52; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_6mpi4py_3MPI_Prequest = __Pyx_ImportType("mpi4py.MPI", "Prequest", sizeof(PyMPIPrequestObject)); if (unlikely(!__pyx_ptype_6mpi4py_3MPI_Prequest)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_6mpi4py_3MPI_Grequest = __Pyx_ImportType("mpi4py.MPI", "Grequest", sizeof(PyMPIGrequestObject)); if (unlikely(!__pyx_ptype_6mpi4py_3MPI_Grequest)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 58; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_6mpi4py_3MPI_Op = __Pyx_ImportType("mpi4py.MPI", "Op", sizeof(PyMPIOpObject)); if (unlikely(!__pyx_ptype_6mpi4py_3MPI_Op)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 61; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_6mpi4py_3MPI_Group = __Pyx_ImportType("mpi4py.MPI", "Group", sizeof(PyMPIGroupObject)); if (unlikely(!__pyx_ptype_6mpi4py_3MPI_Group)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 64; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_6mpi4py_3MPI_Info = __Pyx_ImportType("mpi4py.MPI", "Info", sizeof(PyMPIInfoObject)); if (unlikely(!__pyx_ptype_6mpi4py_3MPI_Info)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_6mpi4py_3MPI_Errhandler = __Pyx_ImportType("mpi4py.MPI", "Errhandler", sizeof(PyMPIErrhandlerObject)); if (unlikely(!__pyx_ptype_6mpi4py_3MPI_Errhandler)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_6mpi4py_3MPI_Comm = __Pyx_ImportType("mpi4py.MPI", "Comm", sizeof(PyMPICommObject)); if (unlikely(!__pyx_ptype_6mpi4py_3MPI_Comm)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_6mpi4py_3MPI_Intracomm = __Pyx_ImportType("mpi4py.MPI", "Intracomm", sizeof(PyMPIIntracommObject)); if (unlikely(!__pyx_ptype_6mpi4py_3MPI_Intracomm)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 76; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_6mpi4py_3MPI_Cartcomm = __Pyx_ImportType("mpi4py.MPI", "Cartcomm", sizeof(PyMPICartcommObject)); if (unlikely(!__pyx_ptype_6mpi4py_3MPI_Cartcomm)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 79; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_6mpi4py_3MPI_Graphcomm = __Pyx_ImportType("mpi4py.MPI", "Graphcomm", sizeof(PyMPIGraphcommObject)); if (unlikely(!__pyx_ptype_6mpi4py_3MPI_Graphcomm)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_6mpi4py_3MPI_Intercomm = __Pyx_ImportType("mpi4py.MPI", "Intercomm", sizeof(PyMPIIntercommObject)); if (unlikely(!__pyx_ptype_6mpi4py_3MPI_Intercomm)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 85; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_6mpi4py_3MPI_Win = __Pyx_ImportType("mpi4py.MPI", "Win", sizeof(PyMPIWinObject)); if (unlikely(!__pyx_ptype_6mpi4py_3MPI_Win)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 88; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_6mpi4py_3MPI_File = __Pyx_ImportType("mpi4py.MPI", "File", sizeof(PyMPIFileObject)); if (unlikely(!__pyx_ptype_6mpi4py_3MPI_File)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 91; __pyx_clineno = __LINE__; goto __pyx_L1;}
  /*--- Function import code ---*/
  /*--- Execution code ---*/

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":7
 * # (file: mpi4py/MPI.so)
 * 
 * from mpi4py import MPI             # <<<<<<<<<<<<<<
 * 
 * # Python-level objects and code
 */
  __pyx_1 = PyList_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_kp_MPI);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_kp_MPI);
  __pyx_2 = __Pyx_Import(__pyx_kp_1, ((PyObject *)__pyx_1)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_kp_MPI); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_MPI, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":11
 * # Python-level objects and code
 * 
 * size  = MPI.COMM_WORLD.Get_size()             # <<<<<<<<<<<<<<
 * rank  = MPI.COMM_WORLD.Get_rank()
 * pname = MPI.Get_processor_name()
 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_kp_MPI); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_kp_COMM_WORLD); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_kp_Get_size); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_size, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":12
 * 
 * size  = MPI.COMM_WORLD.Get_size()
 * rank  = MPI.COMM_WORLD.Get_rank()             # <<<<<<<<<<<<<<
 * pname = MPI.Get_processor_name()
 * 
 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_kp_MPI); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_kp_COMM_WORLD); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_kp_Get_rank); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_rank, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":13
 * size  = MPI.COMM_WORLD.Get_size()
 * rank  = MPI.COMM_WORLD.Get_rank()
 * pname = MPI.Get_processor_name()             # <<<<<<<<<<<<<<
 * 
 * hwmess = "Hello, World! I am process %d of %d on %s."
 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_kp_MPI); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_kp_Get_processor_name); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_pname, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":15
 * pname = MPI.Get_processor_name()
 * 
 * hwmess = "Hello, World! I am process %d of %d on %s."             # <<<<<<<<<<<<<<
 * print (hwmess % (rank, size, pname))
 * 
 */
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_hwmess, __pyx_kp_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1;}

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":16
 * 
 * hwmess = "Hello, World! I am process %d of %d on %s."
 * print (hwmess % (rank, size, pname))             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_kp_hwmess); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_kp_rank); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_kp_size); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_kp_pname); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(3); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_2);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_3);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_4);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_2 = PyNumber_Remainder(__pyx_1, ((PyObject *)__pyx_5)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_5)); __pyx_5 = 0;
  __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  if (__Pyx_Print(((PyObject *)__pyx_3), 1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":32
 * # C-level cdef, typed, Python objects
 * 
 * cdef CommType WORLD = MPI.COMM_WORLD             # <<<<<<<<<<<<<<
 * cdef IntracommType SELF = MPI.COMM_SELF
 * 
 */
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_kp_MPI); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_1 = PyObject_GetAttr(__pyx_4, __pyx_kp_COMM_WORLD); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (!(__Pyx_TypeTest(__pyx_1, __pyx_ptype_6mpi4py_3MPI_Comm))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_v_9distarray_3mpi_5tests_10helloworld_WORLD = ((PyMPICommObject *)__pyx_1);
  __pyx_1 = 0;


  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":33
 * 
 * cdef CommType WORLD = MPI.COMM_WORLD
 * cdef IntracommType SELF = MPI.COMM_SELF             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_kp_MPI); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_5, __pyx_kp_COMM_SELF); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  if (!(__Pyx_TypeTest(__pyx_2, __pyx_ptype_6mpi4py_3MPI_Intracomm))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_v_9distarray_3mpi_5tests_10helloworld_SELF = ((PyMPIIntracommObject *)__pyx_2);
  __pyx_2 = 0;


  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":46
 * cimport mpi4py.mpi_c as mpi
 * 
 * cdef mpi.MPI_Comm world1 = WORLD.ob_mpi             # <<<<<<<<<<<<<<
 * cdef mpi.MPI_Comm world2 = WORLD.comm
 * 
 */
  __pyx_v_9distarray_3mpi_5tests_10helloworld_world1 = __pyx_v_9distarray_3mpi_5tests_10helloworld_WORLD->ob_mpi;


  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":47
 * 
 * cdef mpi.MPI_Comm world1 = WORLD.ob_mpi
 * cdef mpi.MPI_Comm world2 = WORLD.comm             # <<<<<<<<<<<<<<
 * 
 * cdef int ierr1=0
 */
  __pyx_v_9distarray_3mpi_5tests_10helloworld_world2 = __pyx_v_9distarray_3mpi_5tests_10helloworld_WORLD->ob_mpi;


  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":49
 * cdef mpi.MPI_Comm world2 = WORLD.comm
 * 
 * cdef int ierr1=0             # <<<<<<<<<<<<<<
 * 
 * cdef int size1 = 0
 */
  __pyx_v_9distarray_3mpi_5tests_10helloworld_ierr1 = 0;


  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":51
 * cdef int ierr1=0
 * 
 * cdef int size1 = 0             # <<<<<<<<<<<<<<
 * ierr1 = mpi.MPI_Comm_size(mpi.MPI_COMM_WORLD, &size1)
 * 
 */
  __pyx_v_9distarray_3mpi_5tests_10helloworld_size1 = 0;


  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":52
 * 
 * cdef int size1 = 0
 * ierr1 = mpi.MPI_Comm_size(mpi.MPI_COMM_WORLD, &size1)             # <<<<<<<<<<<<<<
 * 
 * cdef int rank1 = 0
 */
  __pyx_v_9distarray_3mpi_5tests_10helloworld_ierr1 = MPI_Comm_size(MPI_COMM_WORLD, (&__pyx_v_9distarray_3mpi_5tests_10helloworld_size1));

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":54
 * ierr1 = mpi.MPI_Comm_size(mpi.MPI_COMM_WORLD, &size1)
 * 
 * cdef int rank1 = 0             # <<<<<<<<<<<<<<
 * ierr1 = mpi.MPI_Comm_rank(mpi.MPI_COMM_WORLD, &rank1)
 * 
 */
  __pyx_v_9distarray_3mpi_5tests_10helloworld_rank1 = 0;


  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":55
 * 
 * cdef int rank1 = 0
 * ierr1 = mpi.MPI_Comm_rank(mpi.MPI_COMM_WORLD, &rank1)             # <<<<<<<<<<<<<<
 * 
 * cdef int rlen1=0
 */
  __pyx_v_9distarray_3mpi_5tests_10helloworld_ierr1 = MPI_Comm_rank(MPI_COMM_WORLD, (&__pyx_v_9distarray_3mpi_5tests_10helloworld_rank1));

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":57
 * ierr1 = mpi.MPI_Comm_rank(mpi.MPI_COMM_WORLD, &rank1)
 * 
 * cdef int rlen1=0             # <<<<<<<<<<<<<<
 * cdef char pname1[mpi.MPI_MAX_PROCESSOR_NAME]
 * ierr1 = mpi.MPI_Get_processor_name(pname1, &rlen1)
 */
  __pyx_v_9distarray_3mpi_5tests_10helloworld_rlen1 = 0;


  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":59
 * cdef int rlen1=0
 * cdef char pname1[mpi.MPI_MAX_PROCESSOR_NAME]
 * ierr1 = mpi.MPI_Get_processor_name(pname1, &rlen1)             # <<<<<<<<<<<<<<
 * pname1[rlen1] = 0 # just in case ;-)
 * 
 */
  __pyx_v_9distarray_3mpi_5tests_10helloworld_ierr1 = MPI_Get_processor_name(__pyx_v_9distarray_3mpi_5tests_10helloworld_pname1, (&__pyx_v_9distarray_3mpi_5tests_10helloworld_rlen1));

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":60
 * cdef char pname1[mpi.MPI_MAX_PROCESSOR_NAME]
 * ierr1 = mpi.MPI_Get_processor_name(pname1, &rlen1)
 * pname1[rlen1] = 0 # just in case ;-)             # <<<<<<<<<<<<<<
 * 
 * hwmess = "Hello, World! I am process %d of %d on %s."
 */
  (__pyx_v_9distarray_3mpi_5tests_10helloworld_pname1[__pyx_v_9distarray_3mpi_5tests_10helloworld_rlen1]) = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":62
 * pname1[rlen1] = 0 # just in case ;-)
 * 
 * hwmess = "Hello, World! I am process %d of %d on %s."             # <<<<<<<<<<<<<<
 * print (hwmess % (rank1, size1, pname1))
 * 
 */
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_hwmess, __pyx_kp_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; __pyx_clineno = __LINE__; goto __pyx_L1;}

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":63
 * 
 * hwmess = "Hello, World! I am process %d of %d on %s."
 * print (hwmess % (rank1, size1, pname1))             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_kp_hwmess); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(__pyx_v_9distarray_3mpi_5tests_10helloworld_rank1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_1 = PyInt_FromLong(__pyx_v_9distarray_3mpi_5tests_10helloworld_size1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_5 = __Pyx_PyBytes_FromString(__pyx_v_9distarray_3mpi_5tests_10helloworld_pname1); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(3); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_1);
  PyTuple_SET_ITEM(__pyx_2, 2, __pyx_5);
  __pyx_4 = 0;
  __pyx_1 = 0;
  __pyx_5 = 0;
  __pyx_4 = PyNumber_Remainder(__pyx_3, ((PyObject *)__pyx_2)); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_4);
  __pyx_4 = 0;
  if (__Pyx_Print(((PyObject *)__pyx_1), 1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":76
 * include "mpi4py/mpi.pxi"
 * 
 * cdef MPI_Comm world3 = WORLD.ob_mpi             # <<<<<<<<<<<<<<
 * cdef MPI_Comm world4 = WORLD.comm
 * 
 */
  __pyx_v_9distarray_3mpi_5tests_10helloworld_world3 = __pyx_v_9distarray_3mpi_5tests_10helloworld_WORLD->ob_mpi;


  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":77
 * 
 * cdef MPI_Comm world3 = WORLD.ob_mpi
 * cdef MPI_Comm world4 = WORLD.comm             # <<<<<<<<<<<<<<
 * 
 * cdef int ierr2=0
 */
  __pyx_v_9distarray_3mpi_5tests_10helloworld_world4 = __pyx_v_9distarray_3mpi_5tests_10helloworld_WORLD->ob_mpi;


  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":79
 * cdef MPI_Comm world4 = WORLD.comm
 * 
 * cdef int ierr2=0             # <<<<<<<<<<<<<<
 * 
 * cdef int size2 = 0
 */
  __pyx_v_9distarray_3mpi_5tests_10helloworld_ierr2 = 0;


  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":81
 * cdef int ierr2=0
 * 
 * cdef int size2 = 0             # <<<<<<<<<<<<<<
 * ierr2 = MPI_Comm_size(MPI_COMM_WORLD, &size2)
 * 
 */
  __pyx_v_9distarray_3mpi_5tests_10helloworld_size2 = 0;


  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":82
 * 
 * cdef int size2 = 0
 * ierr2 = MPI_Comm_size(MPI_COMM_WORLD, &size2)             # <<<<<<<<<<<<<<
 * 
 * cdef int rank2 = 0
 */
  __pyx_v_9distarray_3mpi_5tests_10helloworld_ierr2 = MPI_Comm_size(MPI_COMM_WORLD, (&__pyx_v_9distarray_3mpi_5tests_10helloworld_size2));

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":84
 * ierr2 = MPI_Comm_size(MPI_COMM_WORLD, &size2)
 * 
 * cdef int rank2 = 0             # <<<<<<<<<<<<<<
 * ierr2 = MPI_Comm_rank(MPI_COMM_WORLD, &rank2)
 * 
 */
  __pyx_v_9distarray_3mpi_5tests_10helloworld_rank2 = 0;


  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":85
 * 
 * cdef int rank2 = 0
 * ierr2 = MPI_Comm_rank(MPI_COMM_WORLD, &rank2)             # <<<<<<<<<<<<<<
 * 
 * cdef int rlen2=0
 */
  __pyx_v_9distarray_3mpi_5tests_10helloworld_ierr2 = MPI_Comm_rank(MPI_COMM_WORLD, (&__pyx_v_9distarray_3mpi_5tests_10helloworld_rank2));

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":87
 * ierr2 = MPI_Comm_rank(MPI_COMM_WORLD, &rank2)
 * 
 * cdef int rlen2=0             # <<<<<<<<<<<<<<
 * cdef char pname2[MPI_MAX_PROCESSOR_NAME]
 * ierr2 = MPI_Get_processor_name(pname2, &rlen2)
 */
  __pyx_v_9distarray_3mpi_5tests_10helloworld_rlen2 = 0;


  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":89
 * cdef int rlen2=0
 * cdef char pname2[MPI_MAX_PROCESSOR_NAME]
 * ierr2 = MPI_Get_processor_name(pname2, &rlen2)             # <<<<<<<<<<<<<<
 * pname2[rlen2] = 0 # just in case ;-)
 * 
 */
  __pyx_v_9distarray_3mpi_5tests_10helloworld_ierr2 = MPI_Get_processor_name(__pyx_v_9distarray_3mpi_5tests_10helloworld_pname2, (&__pyx_v_9distarray_3mpi_5tests_10helloworld_rlen2));

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":90
 * cdef char pname2[MPI_MAX_PROCESSOR_NAME]
 * ierr2 = MPI_Get_processor_name(pname2, &rlen2)
 * pname2[rlen2] = 0 # just in case ;-)             # <<<<<<<<<<<<<<
 * 
 * hwmess = "Hello, World! I am process %d of %d on %s."
 */
  (__pyx_v_9distarray_3mpi_5tests_10helloworld_pname2[__pyx_v_9distarray_3mpi_5tests_10helloworld_rlen2]) = 0;

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":92
 * pname2[rlen2] = 0 # just in case ;-)
 * 
 * hwmess = "Hello, World! I am process %d of %d on %s."             # <<<<<<<<<<<<<<
 * print (hwmess % (rank2, size2, pname2))
 * 
 */
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_hwmess, __pyx_kp_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1;}

  /* "/Users/bgranger/Documents/Computation/IPython/branches/ipythondistarray/distarray/mpi/tests/helloworld.pyx":93
 * 
 * hwmess = "Hello, World! I am process %d of %d on %s."
 * print (hwmess % (rank2, size2, pname2))             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_kp_hwmess); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_9distarray_3mpi_5tests_10helloworld_rank2); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(__pyx_v_9distarray_3mpi_5tests_10helloworld_size2); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = __Pyx_PyBytes_FromString(__pyx_v_9distarray_3mpi_5tests_10helloworld_pname2); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(3); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_3);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_2);
  PyTuple_SET_ITEM(__pyx_1, 2, __pyx_4);
  __pyx_3 = 0;
  __pyx_2 = 0;
  __pyx_4 = 0;
  __pyx_3 = PyNumber_Remainder(__pyx_5, ((PyObject *)__pyx_1)); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
  __pyx_3 = 0;
  if (__Pyx_Print(((PyObject *)__pyx_2), 1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  #if PY_MAJOR_VERSION < 3
  return;
  #else
  return __pyx_m;
  #endif
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("distarray.mpi.tests.helloworld");
  #if PY_MAJOR_VERSION >= 3
  return NULL;
  #endif
}

static const char *__pyx_filenames[] = {
  "helloworld.pyx",
  "mpi4py.MPI.pxd",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

#if PY_MAJOR_VERSION < 3
static PyObject *__Pyx_GetStdout(void) {
    PyObject *f = PySys_GetObject("stdout");
    if (!f) {
        PyErr_SetString(PyExc_RuntimeError, "lost sys.stdout");
    }
    return f;
}

static int __Pyx_Print(PyObject *arg_tuple, int newline) {
    PyObject *f;
    PyObject* v;
    int i;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    for (i=0; i < PyTuple_GET_SIZE(arg_tuple); i++) {
        if (PyFile_SoftSpace(f, 1)) {
            if (PyFile_WriteString(" ", f) < 0)
                return -1;
        }
        v = PyTuple_GET_ITEM(arg_tuple, i);
        if (PyFile_WriteObject(v, f, Py_PRINT_RAW) < 0)
            return -1;
        if (PyString_Check(v)) {
            char *s = PyString_AsString(v);
            Py_ssize_t len = PyString_Size(v);
            if (len > 0 &&
                isspace(Py_CHARMASK(s[len-1])) &&
                s[len-1] != ' ')
                    PyFile_SoftSpace(f, 0);
        }
    }
    if (newline) {
        if (PyFile_WriteString("\n", f) < 0)
            return -1;
        PyFile_SoftSpace(f, 0);
    }
    return 0;
}

#else /* Python 3 has a print function */
static int __Pyx_Print(PyObject *arg_tuple, int newline) {
    PyObject* kwargs = 0;
    PyObject* result = 0;
    PyObject* end_string;
    if (!__pyx_print) {
        __pyx_print = PyObject_GetAttrString(__pyx_b, "print");
        if (!__pyx_print)
            return -1;
    }
    if (!newline) {
        if (!__pyx_print_kwargs) {
            __pyx_print_kwargs = PyDict_New();
            if (!__pyx_print_kwargs)
                return -1;
            end_string = PyUnicode_FromStringAndSize(" ", 1);
            if (!end_string)
                return -1;
            if (PyDict_SetItemString(__pyx_print_kwargs, "end", end_string) < 0) {
                Py_DECREF(end_string);
                return -1;
            }
            Py_DECREF(end_string);
        }
        kwargs = __pyx_print_kwargs;
    }
    result = PyObject_Call(__pyx_print, arg_tuple, kwargs);
    if (!result)
        return -1;
    Py_DECREF(result);
    return 0;
}
#endif

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        Py_TYPE(obj)->tp_name, type->tp_name);
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        #if PY_MAJOR_VERSION < 3
        if (t->is_unicode && (!t->is_identifier)) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else if (t->intern) {
            *t->p = PyString_InternFromString(t->s);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        #else  /* Python 3+ has unicode identifiers */
        if (t->is_identifier || (t->is_unicode && t->intern)) {
            *t->p = PyUnicode_InternFromString(t->s);
        } else if (t->is_unicode) {
            *t->p = PyUnicode_FromStringAndSize(t->s, t->n - 1);
        } else {
            *t->p = PyBytes_FromStringAndSize(t->s, t->n - 1);
        }
        #endif
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#ifndef __PYX_HAVE_RT_ImportType
#define __PYX_HAVE_RT_ImportType
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name,
    long size)
{
    PyObject *py_module = 0;
    PyObject *result = 0;
    PyObject *py_name = 0;

    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(module_name);
    #else
    py_name = PyUnicode_FromString(module_name);
    #endif
    if (!py_name)
        goto bad;

    py_module = __Pyx_ImportModule(module_name);
    if (!py_module)
        goto bad;
    result = PyObject_GetAttrString(py_module, class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(py_name);
    Py_XDECREF(result);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(char *name) {
    PyObject *py_name = 0;
    PyObject *py_module = 0;

    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(name);
    #else
    py_name = PyUnicode_FromString(name);
    #endif
    if (!py_name)
        goto bad;
    py_module = PyImport_Import(py_name);
    Py_DECREF(py_name);
    return py_module;
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(const char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;

    #if PY_MAJOR_VERSION < 3
    py_srcfile = PyString_FromString(__pyx_filename);
    #else
    py_srcfile = PyUnicode_FromString(__pyx_filename);
    #endif
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromFormat( "%s (%s:%u)", funcname, __pyx_cfilenm, __pyx_clineno);
        #else
        py_funcname = PyUnicode_FromFormat( "%s (%s:%u)", funcname, __pyx_cfilenm, __pyx_clineno);
        #endif
    }
    else {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromString(funcname);
        #else
        py_funcname = PyUnicode_FromString(funcname);
        #endif
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    #if PY_MAJOR_VERSION < 3
    empty_string = PyString_FromStringAndSize("", 0);
    #else
    empty_string = PyBytes_FromStringAndSize("", 0);
    #endif
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        #if PY_MAJOR_VERSION >= 3
        0,            /*int kwonlyargcount,*/
        #endif
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}
